spring:
  datasource:
    url: jdbc:oracle:thin:@192.168.178.214:1521:afclc
    username: acc_xuzhou_v1
    password: 9*%BC%B4-4%AD%EA

#节点服务地址
topologyServerUrl: http://192.168.178.185:9080
#ms地址
rmiHostIpAddr: 192.168.178.185
#权限服务地址
security:
  server: http://192.168.178.185:18080
server:
  port: 9081