spring:
  datasource:
    url: jdbc:oracle:thin:@192.168.178.212:1521:afclc
    username: mlc_cd_v1
    password: 9*%BC%B4-4%AD%EA

#tomcat配置
server:
  port: 8083

refreshcycle: 5

security:
  server: http://192.168.178.184:8081

#节点服务地址
topology-server-url: http://192.168.178.184:8082