spring:
  datasource:
    url: jdbc:oracle:thin:@192.168.178.214:1521:afclc
    username: acc_wenzhou_v2
    password: afcapp

#节点服务地址
topology-server-url: http://localhost:8080
rmiHostIpAddr: 127.0.0.1