spring:
  datasource:
    url: jdbc:oracle:thin:@192.168.178.212:1521:afclc
    username: mlc_cd_v1
    password: 9*%BC%B4-4%AD%EA
#本机地址和端口
server:
  address: 192.168.178.184
  port: 8083
#节点服务地址
topology-server-url: http://192.168.178.184:8082
#权限服务地址
security:
  server: http://192.168.178.184:8081
#MS地址
rmiHostIpAddr: 192.168.178.185
#与MessageServer通讯RMI配置
communicationRegistRmiPort: 8527
commandServiceRmiPort: 8528
