spring:
  datasource:
    url: jdbc:oracle:thin:@192.168.178.212:1521:afclc
    username: mlc_cd_v1
    password: afcapp

#节点服务地址
topology-server-url: http://localhost:8080
rmiHostIpAddr: 192.168.178.176