spring:
  datasource:
    url: jdbc:oracle:thin:@192.168.178.214:1521:afclc
    username: acc_xuzhou_v1
    password: afcapp

#节点服务地址
topologyServerUrl: http://192.168.140.100:9080
rmiHostIpAddr: 192.168.178.176