#tomcat配置
server:
  tomcat:
    #文件上传临时目录
    basedir: ./tmp
    uri-encoding: UTF-8
    accesslog:
      enabled: false

#spring配置
spring:
  application:
    name: monitor
  profiles:
    active: pro
  #http编码配置
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  #数据源配置
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    type: com.insigma.commons.datasource.EncryptedDataSource
    dbcp2:
      initial-size: 5
      min-idle: 3
      max-idle: 20
      max-total: 50
      max-wait-millis: 600000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true

  #servlet配置
  servlet:
    multipart:
      #上传文件最大1MB
      max-file-size: 1MB
  #jpa配置
  jpa:
    open-in-view: false
    show-sql: true
  #json序列化配置
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  pid:
    fail-on-write-error: true

#监控配置
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
      base-path: /actuator

#api信息
api:
  title: 监控服务接口
  description:
  version: 1.0
  termsOfServiceUrl: "http://www.unittec.com/"
  license:
  licenseUrl:
  contactName: xuzhemin
  contactUrl:
  contactEmail: xuzhemin@unittec.com

#车站基本配置
info:
  app:
    applicationName: 成都MLC监控
    lineNo: 0
    stationNo: 0
    nodeNo: 0x00000000

#与MessageServer通讯RMI配置
communicationRegistRmiPort: 8527
commandServiceRmiPort: 8528