#api信息
api:
  title: 监控服务接口
  description:
  version: 1.0
  termsOfServiceUrl: "http://www.unittec.com/"
  license:
  licenseUrl:
  contactName: xuzhemin
  contactUrl:
  contactEmail: xuzhemin@unittec.com

#车站基本配置
info:
  app:
    applicationName: 徐州ACC监控
    lineNo: 0
    stationNo: 0
    nodeNo: 0x00000000

#tomcat配置
server:
  port: 8081
  tomcat:
    #文件上传临时目录
    basedir: ./tmp

spring:
  profiles:
    active: dev
  #数据源配置
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    type: org.apache.commons.dbcp2.BasicDataSource
  #servlet配置
  servlet:
    multipart:
      #上传文件最大1MB
      max-file-size: 1MB
  #jpa配置
  jpa:
    open-in-view: false
    show-sql: false
  application:
    name: monitor-service
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  pid:
    fail-on-write-error: true

#监控配置
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
      base-path: /actuator

#与MessageServer通讯RMI配置
communicationRegistRmiPort: 8527
commandServiceRmiPort: 8528