spring:
  datasource:
    url: jdbc:oracle:thin:@192.168.178.212:1521:afclc
    username: mlc_cd_v1
    password: afcapp
topology-server-url: http://192.168.178.184:8060
rmiHostIpAddr: 192.168.178.185
security:
  server: http://192.168.178.184:18080
server:
  port: 8070