delete from tap_component_control_data t where t.version_record_id in (select m.record_id from tap_master_control_data m where m.file_type=32);
delete from tap_master_control_data t where t.file_type=32;
delete from TPA_ADItem_t;
delete from TPA_AGMControlDefinition_t;
delete from TPA_AddValueBtn_t;
delete from TPA_BOMControlDefinition_t;
delete from TPA_BankAddingValuePara_t;
delete from TPA_BaseFare_t;
delete from TPA_ChipDefinition_t;
delete from TPA_ConcessionalLampType_t;
delete from TPA_DeviceLoginParam_t;
delete from TPA_DisplayWindow_t;
delete from TPA_EOD_AGMParam_t;
delete from TPA_EOD_BOMParam_t;
delete from TPA_EOD_CalendarParam_t;
delete from TPA_EOD_ConcessionParam_t;
delete from TPA_EOD_FareParam_t;
delete from TPA_EOD_ISMParam_t;
delete from TPA_EOD_NetworkTopologyParam_t;
delete from TPA_EOD_PCAParam_t;
delete from TPA_EOD_RGParamList_t;
delete from TPA_EOD_RGParam_t;
delete from TPA_EOD_SLESoftParam_t;
delete from TPA_EOD_SystemParam_t;
delete from TPA_EOD_TPSoftParam_t;
delete from TPA_EOD_TVMParam_t;
delete from TPA_EOD_TVM_GUIParam_t;
delete from TPA_EOD_TicketParam_t;
delete from TPA_ExpressBtnForBOM_t;
delete from TPA_ExpressBtn_t;
delete from TPA_FareGroup_t;
delete from TPA_FareTierMatrix_t;
delete from TPA_FareTierTimeTable_t;
delete from TPA_ISMControlDefinition_t;
delete from TPA_IntervalOfMakeFile_t;
delete from TPA_JoinConcessionDefinition_t;
delete from TPA_LineBtn_t;
delete from TPA_Line_t;
delete from TPA_NumbersBtn_t;
delete from TPA_PCAControlDefinition_t;
delete from TPA_PassageModeInfo_t;
delete from TPA_PayInterfacePosition_t;
delete from TPA_PileConcessionDefinition_t;
delete from TPA_ResourceFile_t;
delete from TPA_SCUploadFile_t;
delete from TPA_ScreenSize_t;
delete from TPA_SoundDisplay_t;
delete from TPA_SpecialDate_t;
delete from TPA_StationBtnInLineZone_t;
delete from TPA_StationBtnInLine_t;
delete from TPA_Station_t;
delete from TPA_SysTimeSync_t;
delete from TPA_TVMControlDefinition_t;
delete from TPA_TVMGUI_t;
delete from TPA_TicketDefinition_t;
delete from TPA_TicketTypeMap_t;
delete from TPA_TimeInterval_t;
delete from TPA_TopBoard_t;
delete from TPA_TransferStationList_t;
delete from TPA_TransferStation_t;
delete from TPA_ValidBillTypes;
delete from TPA_ValidCoinTypes;





drop table TPA_ADItem_t cascade constraints;
drop table TPA_AGMControlDefinition_t cascade constraints;
drop table TPA_AddValueBtn_t cascade constraints;
drop table TPA_BOMControlDefinition_t cascade constraints;
drop table TPA_BankAddingValuePara_t cascade constraints;
drop table TPA_BaseFare_t cascade constraints;
drop table TPA_ChipDefinition_t cascade constraints;
drop table TPA_ConcessionalLampType_t cascade constraints;
drop table TPA_DeviceLoginParam_t cascade constraints;
drop table TPA_DisplayWindow_t cascade constraints;
drop table TPA_EOD_AGMParam_t cascade constraints;
drop table TPA_EOD_BOMParam_t cascade constraints;
drop table TPA_EOD_CalendarParam_t cascade constraints;
drop table TPA_EOD_ConcessionParam_t cascade constraints;
drop table TPA_EOD_FareParam_t cascade constraints;
drop table TPA_EOD_ISMParam_t cascade constraints;
drop table TPA_EOD_NetworkTopologyParam_t cascade constraints;
drop table TPA_EOD_PCAParam_t cascade constraints;
drop table TPA_EOD_RGParamList_t cascade constraints;
drop table TPA_EOD_RGParam_t cascade constraints;
drop table TPA_EOD_SLESoftParam_t cascade constraints;
drop table TPA_EOD_SystemParam_t cascade constraints;
drop table TPA_EOD_TPSoftParam_t cascade constraints;
drop table TPA_EOD_TVMParam_t cascade constraints;
drop table TPA_EOD_TVM_GUIParam_t cascade constraints;
drop table TPA_EOD_TicketParam_t cascade constraints;
drop table TPA_ExpressBtnForBOM_t cascade constraints;
drop table TPA_ExpressBtn_t cascade constraints;
drop table TPA_FareGroup_t cascade constraints;
drop table TPA_FareTierMatrix_t cascade constraints;
drop table TPA_FareTierTimeTable_t cascade constraints;
drop table TPA_ISMControlDefinition_t cascade constraints;
drop table TPA_IntervalOfMakeFile_t cascade constraints;
drop table TPA_JoinConcessionDefinition_t cascade constraints;
drop table TPA_LineBtn_t cascade constraints;
drop table TPA_Line_t cascade constraints;
drop table TPA_NumbersBtn_t cascade constraints;
drop table TPA_PCAControlDefinition_t cascade constraints;
drop table TPA_PassageModeInfo_t cascade constraints;
drop table TPA_PayInterfacePosition_t cascade constraints;
drop table TPA_PileConcessionDefinition_t cascade constraints;
drop table TPA_ResourceFile_t cascade constraints;
drop table TPA_SCUploadFile_t cascade constraints;
drop table TPA_ScreenSize_t cascade constraints;
drop table TPA_SoundDisplay_t cascade constraints;
drop table TPA_SpecialDate_t cascade constraints;
drop table TPA_StationBtnInLineZone_t cascade constraints;
drop table TPA_StationBtnInLine_t cascade constraints;
drop table TPA_Station_t cascade constraints;
drop table TPA_SysTimeSync_t cascade constraints;
drop table TPA_TVMControlDefinition_t cascade constraints;
drop table TPA_TVMGUI_t cascade constraints;
drop table TPA_TicketDefinition_t cascade constraints;
drop table TPA_TicketTypeMap_t cascade constraints;
drop table TPA_TimeInterval_t cascade constraints;
drop table TPA_TopBoard_t cascade constraints;
drop table TPA_TransferStationList_t cascade constraints;
drop table TPA_TransferStation_t cascade constraints;
drop table TPA_ValidBillTypes cascade constraints;
drop table TPA_ValidCoinTypes cascade constraints;
drop sequence S_TPA_ADItem_t;
drop sequence S_TPA_AGMControlDefinition_t;
drop sequence S_TPA_AddValueBtn_t;
drop sequence S_TPA_BOMControlDefinition_t;
drop sequence S_TPA_BankAddingValuePara_t;
drop sequence S_TPA_BaseFare_t;
drop sequence S_TPA_ChipDefinition_t;
drop sequence S_TPA_ConcessionalLampType_t;
drop sequence S_TPA_DeviceLoginParam_t;
drop sequence S_TPA_DisplayWindow_t;
drop sequence S_TPA_EOD_AGMParam_t;
drop sequence S_TPA_EOD_BOMParam_t;
drop sequence S_TPA_EOD_CalendarParam_t;
drop sequence S_TPA_EOD_ConcessionParam_t;
drop sequence S_TPA_EOD_FareParam_t;
drop sequence S_TPA_EOD_ISMParam_t;
drop sequence S_TPA_EOD_NetworkTopologyParam;
drop sequence S_TPA_EOD_PCAParam_t;
drop sequence S_TPA_EOD_RGParamList_t;
drop sequence S_TPA_EOD_RGParam_t;
drop sequence S_TPA_EOD_SLESoftParam_t;
drop sequence S_TPA_EOD_SystemParam_t;
drop sequence S_TPA_EOD_TPSoftParam_t;
drop sequence S_TPA_EOD_TVMParam_t;
drop sequence S_TPA_EOD_TVM_GUIParam_t;
drop sequence S_TPA_EOD_TicketParam_t;
drop sequence S_TPA_ExpressBtnForBOM_t;
drop sequence S_TPA_ExpressBtn_t;
drop sequence S_TPA_FareGroup_t;
drop sequence S_TPA_FareTierMatrix_t;
drop sequence S_TPA_FareTierTimeTable_t;
drop sequence S_TPA_ISMControlDefinition_t;
drop sequence S_TPA_IntervalOfMakeFile_t;
drop sequence S_TPA_JoinConcessionDefinition;
drop sequence S_TPA_LineBtn_t;
drop sequence S_TPA_Line_t;
drop sequence S_TPA_NumbersBtn_t;
drop sequence S_TPA_PCAControlDefinition_t;
drop sequence S_TPA_PassageModeInfo_t;
drop sequence S_TPA_PayInterfacePosition_t;
drop sequence S_TPA_PileConcessionDefinition;
drop sequence S_TPA_ResourceFile_t;
drop sequence S_TPA_SCUploadFile_t;
drop sequence S_TPA_ScreenSize_t;
drop sequence S_TPA_SoundDisplay_t;
drop sequence S_TPA_SpecialDate_t;
drop sequence S_TPA_StationBtnInLineZone_t;
drop sequence S_TPA_StationBtnInLine_t;
drop sequence S_TPA_Station_t;
drop sequence S_TPA_SysTimeSync_t;
drop sequence S_TPA_TVMControlDefinition_t;
drop sequence S_TPA_TVMGUI_t;
drop sequence S_TPA_TicketDefinition_t;
drop sequence S_TPA_TicketTypeMap_t;
drop sequence S_TPA_TimeInterval_t;
drop sequence S_TPA_TopBoard_t;
drop sequence S_TPA_TransferStationList_t;
drop sequence S_TPA_TransferStation_t;
create table TPA_ADItem_t (RECORDID NUMBER(19) not null, VERSIONNUMBER NUMBER(19), nodeNo NUMBER(19), ADItemID NUMBER(5), ADType NUMBER(5), ADItemFileName varchar2(255), ADItemFileMD5 varchar2(255), TPA_EOD_ISMParam_t_id NUMBER(19), index_col NUMBER(10), TPA_TVMGUI_t_id NUMBER(19), primary key (RECORDID));
create table TPA_AGMControlDefinition_t (RECORDID NUMBER(19) not null, VERSIONNUMBER NUMBER(19), nodeNo NUMBER(19), SingleFileMaxDeals NUMBER(10), MaxIntervalToRejectSameTicket NUMBER(19), MaxDelayAfterRejectInvalidTick NUMBER(19), MaxWarnOfTicketBox NUMBER(5), PatronQueue NUMBER(5), MaxDelayOfShowPicture NUMBER(19), ReaderWorkInGateInbreak NUMBER(10), MaxWaitAfterReadCard NUMBER(19), MaxIntervalOfShutGate NUMBER(19), MaxStayInGate NUMBER(19), primary key (RECORDID));
create table TPA_AddValueBtn_t (RECORDID NUMBER(19) not null, VERSIONNUMBER NUMBER(19), nodeNo NUMBER(19), AddValueBtnIndex NUMBER(5), AddValueBtnValue NUMBER(10), AddValueBtnDisplay_id NUMBER(19), TPA_EOD_ISMParam_t_id NUMBER(19), index_col NUMBER(10), TPA_TVMGUI_t_id NUMBER(19), primary key (RECORDID));
create table TPA_BOMControlDefinition_t (RECORDID NUMBER(19) not null, VERSIONNUMBER NUMBER(19), nodeNo NUMBER(19), SingleFileMaxDeals NUMBER(10), MaxExitNoOperation NUMBER(19), MinWarnAmountOfTicketBox NUMBER(5), primary key (RECORDID));
create table TPA_BankAddingValuePara_t (RECORDID NUMBER(19) not null, VERSIONNUMBER NUMBER(19), nodeNo NUMBER(19), BankCardPaymentMinAmount NUMBER(10), BankCardPaymentMaxAmount NUMBER(10), primary key (RECORDID));
create table TPA_BaseFare_t (RECORDID NUMBER(19) not null, VERSIONNUMBER NUMBER(19), nodeNo NUMBER(19), FareGroupID varchar2(255), FareTier varchar2(255), FareAmount NUMBER(10), TPA_EOD_FareParam_t_id NUMBER(19), index_col NUMBER(10), primary key (RECORDID));
create table TPA_ChipDefinition_t (RECORDID NUMBER(19) not null, VERSIONNUMBER NUMBER(19), nodeNo NUMBER(19), ChipType NUMBER(10), PhycialValidityPeriod NUMBER(10), MaxChipIONumber NUMBER(19), TPA_EOD_TicketParam_t_id NUMBER(19), index_col NUMBER(10), primary key (RECORDID));
create table TPA_ConcessionalLampType_t (RECORDID NUMBER(19) not null, VERSIONNUMBER NUMBER(19), nodeNo NUMBER(19), ConcessionalLampID NUMBER(5), LampColorTypeID NUMBER(5), Frequency NUMBER(10), DisplayPeriod NUMBER(19), TPA_EOD_AGMParam_t_id NUMBER(19), index_col NUMBER(10), primary key (RECORDID));
create table TPA_DeviceLoginParam_t (RECORDID NUMBER(19) not null, VERSIONNUMBER NUMBER(19), nodeNo NUMBER(19), LoginOvertime NUMBER(19), MaxPINEntryRetries NUMBER(19), primary key (RECORDID));
create table TPA_DisplayWindow_t (RECORDID NUMBER(19) not null, VERSIONNUMBER NUMBER(19), nodeNo NUMBER(19), DisplayPictureX NUMBER(10), DisplayPictureY NUMBER(10), DisplayPictureWidth NUMBER(10), DisplayPictureHeight NUMBER(10), primary key (RECORDID));
create table TPA_EOD_AGMParam_t (RECORDID NUMBER(19) not null, VERSIONNUMBER NUMBER(19), nodeNo NUMBER(19), IntervalOfMakeFile_id NUMBER(19), AGMControlDefinition_id NUMBER(19), primary key (RECORDID));
create table TPA_EOD_BOMParam_t (RECORDID NUMBER(19) not null, VERSIONNUMBER NUMBER(19), nodeNo NUMBER(19), BOMControlDefinition_id NUMBER(19), IntervalOfMakeFile_id NUMBER(19), primary key (RECORDID));
create table TPA_EOD_CalendarParam_t (RECORDID NUMBER(19) not null, VERSIONNUMBER NUMBER(19), nodeNo NUMBER(19), RunStartofDay NUMBER(19), RunStartTime NUMBER(19), RunEndTime NUMBER(19), BalaStartTime NUMBER(19), BalaEndTime NUMBER(19), ClearEndTime NUMBER(19), AccEndTime NUMBER(19), UrgrelDelayTime NUMBER(19), TrainfaultDelayTime NUMBER(19), ModeSenTime NUMBER(19), primary key (RECORDID));
create table TPA_EOD_ConcessionParam_t (RECORDID NUMBER(19) not null, VERSIONNUMBER NUMBER(19), nodeNo NUMBER(19), primary key (RECORDID));
create table TPA_EOD_FareParam_t (RECORDID NUMBER(19) not null, VERSIONNUMBER NUMBER(19), nodeNo NUMBER(19), BankAddingValuePara_id NUMBER(19), primary key (RECORDID));
create table TPA_EOD_ISMParam_t (RECORDID NUMBER(19) not null, VERSIONNUMBER NUMBER(19), nodeNo NUMBER(19), ADPlayType NUMBER(10), MaxIdleToPlayAD NUMBER(19), StartupDisplayPicture_id NUMBER(19), RunningStatusDisplayWindow_id NUMBER(19), IntervalOfMakeFile_id NUMBER(19), StartupDisplayWindow_id NUMBER(19), InfoQueryDisplayWindow_id NUMBER(19), PauseDisplayWindow_id NUMBER(19), ScreenSize_id NUMBER(19), NowStationDisplayWindow_id NUMBER(19), LanguageDisplayWindow_id NUMBER(19), AddValueDisplayWindow_id NUMBER(19), TSMControlDefinition_id NUMBER(19), NowtimeDisplayWindow_id NUMBER(19), CheckCardDisplayWindow_id NUMBER(19), PauseDisplayPicture_id NUMBER(19), primary key (RECORDID));
create table TPA_EOD_NetworkTopologyParam_t (RECORDID NUMBER(19) not null, VERSIONNUMBER NUMBER(19), nodeNo NUMBER(19), primary key (RECORDID));
create table TPA_EOD_PCAParam_t (RECORDID NUMBER(19) not null, VERSIONNUMBER NUMBER(19), nodeNo NUMBER(19), IntervalOfMakeFile_id NUMBER(19), PCAControlDefinition_id NUMBER(19), primary key (RECORDID));
create table TPA_EOD_RGParamList_t (RECORDID NUMBER(19) not null, VERSIONNUMBER NUMBER(19), nodeNo NUMBER(19), primary key (RECORDID));
create table TPA_EOD_RGParam_t (RECORDID NUMBER(19) not null, VERSIONNUMBER NUMBER(19), nodeNo NUMBER(19), DeviceID varchar2(255), TPA_EOD_RGParamList_t_id NUMBER(19), index_col NUMBER(10), primary key (RECORDID));
create table TPA_EOD_SLESoftParam_t (RECORDID NUMBER(19) not null, VERSIONNUMBER NUMBER(19), nodeNo NUMBER(19), TVMSoft_id NUMBER(19), BOMSoft_id NUMBER(19), ISMSoft_id NUMBER(19), AGMSoft_id NUMBER(19), PCASoft_id NUMBER(19), primary key (RECORDID));
create table TPA_EOD_SystemParam_t (RECORDID NUMBER(19) not null, VERSIONNUMBER NUMBER(19), nodeNo NUMBER(19), DeviceLoginParam_id NUMBER(19), SysTimeSync_id NUMBER(19), SCUploadFile_id NUMBER(19), primary key (RECORDID));
create table TPA_EOD_TPSoftParam_t (RECORDID NUMBER(19) not null, VERSIONNUMBER NUMBER(19), nodeNo NUMBER(19), TPSoft_id NUMBER(19), primary key (RECORDID));
create table TPA_EOD_TVMParam_t (RECORDID NUMBER(19) not null, VERSIONNUMBER NUMBER(19), nodeNo NUMBER(19), IntervalOfMakeFile_id NUMBER(19), TVMControlDefinition_id NUMBER(19), primary key (RECORDID));
create table TPA_EOD_TVM_GUIParam_t (RECORDID NUMBER(19) not null, VERSIONNUMBER NUMBER(19), nodeNo NUMBER(19), primary key (RECORDID));
create table TPA_EOD_TicketParam_t (RECORDID NUMBER(19) not null, VERSIONNUMBER NUMBER(19), nodeNo NUMBER(19), primary key (RECORDID));
create table TPA_ExpressBtnForBOM_t (RECORDID NUMBER(19) not null, VERSIONNUMBER NUMBER(19), nodeNo NUMBER(19), BtnIndex NUMBER(5), BuyBtnValue NUMBER(10), FareTier varchar2(255), TPA_EOD_BOMParam_t_id NUMBER(19), index_col NUMBER(10), primary key (RECORDID));
create table TPA_ExpressBtn_t (RECORDID NUMBER(19) not null, VERSIONNUMBER NUMBER(19), nodeNo NUMBER(19), BtnIndex NUMBER(5), BuyBtnValue NUMBER(10), FareTier varchar2(255), BuyBtnDisplay_id NUMBER(19), TPA_TVMGUI_t_id NUMBER(19), index_col NUMBER(10), primary key (RECORDID));
create table TPA_FareGroup_t (RECORDID NUMBER(19) not null, VERSIONNUMBER NUMBER(19), nodeNo NUMBER(19), TicketType varchar2(255), DateTypeID NUMBER(10), TimeIntervalID NUMBER(5), FareGroupID varchar2(255), TPA_EOD_FareParam_t_id NUMBER(19), index_col NUMBER(10), primary key (RECORDID));
create table TPA_FareTierMatrix_t (RECORDID NUMBER(19) not null, VERSIONNUMBER NUMBER(19), nodeNo NUMBER(19), FareTier varchar2(255), StationIDIn varchar2(255), StationIDOut varchar2(255), TPA_EOD_FareParam_t_id NUMBER(19), index_col NUMBER(10), primary key (RECORDID));
create table TPA_FareTierTimeTable_t (RECORDID NUMBER(19) not null, VERSIONNUMBER NUMBER(19), nodeNo NUMBER(19), FareTier varchar2(255), AllowedTravelPeriod NUMBER(19), TPA_EOD_CalendarParam_t_id NUMBER(19), index_col NUMBER(10), primary key (RECORDID));
create table TPA_ISMControlDefinition_t (RECORDID NUMBER(19) not null, VERSIONNUMBER NUMBER(19), nodeNo NUMBER(19), SingleFileMaxDeals NUMBER(10), MaxIdleToCancelDeal NUMBER(19), AlmostFullLimitOfBillBox NUMBER(19), FullLimitOfBillBox NUMBER(19), MaxMoneyOfCashAddValue NUMBER(10), primary key (RECORDID));
create table TPA_IntervalOfMakeFile_t (RECORDID NUMBER(19) not null, VERSIONNUMBER NUMBER(19), nodeNo NUMBER(19), IntervalOfBuildYPTUDFile NUMBER(19), IntervalOfBuildYKTUDFile NUMBER(19), IntervalOfBuildARFile NUMBER(19), primary key (RECORDID));
create table TPA_JoinConcessionDefinition_t (RECORDID NUMBER(19) not null, VERSIONNUMBER NUMBER(19), nodeNo NUMBER(19), JoinConcessionID varchar2(255), JoinConcessionIndustryScope varchar2(255), JoinConcessionValidTime NUMBER(10), JoinConcessionType NUMBER(5), JoinConcessionAmount NUMBER(10), JoinConcessionPercentage NUMBER(5), TPA_EOD_ConcessionParam_t_id NUMBER(19), index_col NUMBER(10), primary key (RECORDID));
create table TPA_LineBtn_t (RECORDID NUMBER(19) not null, VERSIONNUMBER NUMBER(19), nodeNo NUMBER(19), LineID varchar2(255), LineBtnEnableFlag NUMBER(10), LineBtnDisplay_id NUMBER(19), LineDisplay_id NUMBER(19), CNLinePicture_id NUMBER(19), ENLinePicture_id NUMBER(19), TPA_TVMGUI_t_id NUMBER(19), index_col NUMBER(10), primary key (RECORDID));
create table TPA_Line_t (RECORDID NUMBER(19) not null, VERSIONNUMBER NUMBER(19), nodeNo NUMBER(19), LineID varchar2(255), LineCNName varchar2(255), LineENName varchar2(255), EnableFlag NUMBER(10), TPA_EOD_NetworkTopologyPara_id NUMBER(19), index_col NUMBER(10), primary key (RECORDID));
create table TPA_NumbersBtn_t (RECORDID NUMBER(19) not null, VERSIONNUMBER NUMBER(19), nodeNo NUMBER(19), BtnIndex NUMBER(5), TicketQuantity NUMBER(19), NumbersBtnDisplay_id NUMBER(19), TPA_TVMGUI_t_id NUMBER(19), index_col NUMBER(10), primary key (RECORDID));
create table TPA_PCAControlDefinition_t (RECORDID NUMBER(19) not null, VERSIONNUMBER NUMBER(19), nodeNo NUMBER(19), SingleFileMaxDeals NUMBER(10), MaxIdleToCancelDeal NUMBER(19), primary key (RECORDID));
create table TPA_PassageModeInfo_t (RECORDID NUMBER(19) not null, VERSIONNUMBER NUMBER(19), nodeNo NUMBER(19), PassageMode NUMBER(5), BeginTime NUMBER(19), EndTime NUMBER(19), TPA_EOD_RGParam_t_id NUMBER(19), index_col NUMBER(10), primary key (RECORDID));
create table TPA_PayInterfacePosition_t (RECORDID NUMBER(19) not null, VERSIONNUMBER NUMBER(19), nodeNo NUMBER(19), PosType NUMBER(5), PosDisplay_id NUMBER(19), TPA_TVMGUI_t_id NUMBER(19), index_col NUMBER(10), primary key (RECORDID));
create table TPA_PileConcessionDefinition_t (RECORDID NUMBER(19) not null, VERSIONNUMBER NUMBER(19), nodeNo NUMBER(19), PileConcessionID varchar2(255), PileConcessionType NUMBER(5), PileConcessionTime NUMBER(19), PileConcessionAmount NUMBER(10), JoinConcessionPercentage NUMBER(5), ConcessionResetType NUMBER(5), TPA_EOD_ConcessionParam_t_id NUMBER(19), index_col NUMBER(10), primary key (RECORDID));
create table TPA_ResourceFile_t (RECORDID NUMBER(19) not null, VERSIONNUMBER NUMBER(19), nodeNo NUMBER(19), PictureFileName varchar2(255), PictureFileMD5 varchar2(255), primary key (RECORDID));
create table TPA_SCUploadFile_t (RECORDID NUMBER(19) not null, VERSIONNUMBER NUMBER(19), nodeNo NUMBER(19), SingleUDFileMaxDeals NUMBER(10), SingleARFileMaxDeals NUMBER(10), IntervalOfBuildYPTUDFile NUMBER(19), IntervalOfBuildYKTUDFile NUMBER(19), IntervalOfBuildARFile NUMBER(19), IntervalOfBuildStockFile NUMBER(19), primary key (RECORDID));
create table TPA_ScreenSize_t (RECORDID NUMBER(19) not null, VERSIONNUMBER NUMBER(19), nodeNo NUMBER(19), ScreenWidth NUMBER(10), ScreenHeight NUMBER(10), primary key (RECORDID));
create table TPA_SoundDisplay_t (RECORDID NUMBER(19) not null, VERSIONNUMBER NUMBER(19), nodeNo NUMBER(19), SoundDisplayID NUMBER(5), SoundDisplayFileName varchar2(255), SoundDisplayFileMD5 varchar2(255), TPA_EOD_AGMParam_t_id NUMBER(19), index_col NUMBER(10), primary key (RECORDID));
create table TPA_SpecialDate_t (RECORDID NUMBER(19) not null, VERSIONNUMBER NUMBER(19), nodeNo NUMBER(19), SpecialDate timestamp, DateTypeID NUMBER(10), TPA_EOD_CalendarParam_t_id NUMBER(19), index_col NUMBER(10), primary key (RECORDID));
create table TPA_StationBtnInLineZone_t (RECORDID NUMBER(19) not null, VERSIONNUMBER NUMBER(19), nodeNo NUMBER(19), StationID varchar2(255), StationSelBtnEnable NUMBER(10), StationInLineZoneDisplay_id NUMBER(19), TPA_TVMGUI_t_id NUMBER(19), index_col NUMBER(10), primary key (RECORDID));
create table TPA_StationBtnInLine_t (RECORDID NUMBER(19) not null, VERSIONNUMBER NUMBER(19), nodeNo NUMBER(19), StationID varchar2(255), LineID varchar2(255), StationSelBtnEnable NUMBER(10), StationInLineDisplay_id NUMBER(19), TPA_TVMGUI_t_id NUMBER(19), index_col NUMBER(10), primary key (RECORDID));
create table TPA_Station_t (RECORDID NUMBER(19) not null, VERSIONNUMBER NUMBER(19), nodeNo NUMBER(19), StationID varchar2(255), StationCNName varchar2(255), StationENName varchar2(255), LineID varchar2(255), EnableFlag NUMBER(10), TPA_EOD_NetworkTopologyPara_id NUMBER(19), index_col NUMBER(10), primary key (RECORDID));
create table TPA_SysTimeSync_t (RECORDID NUMBER(19) not null, VERSIONNUMBER NUMBER(19), nodeNo NUMBER(19), TimeDeviationPeriod NUMBER(19), MinTimeDeviation NUMBER(19), WarnTimeDeviation NUMBER(19), MaxTimeDeviation NUMBER(19), primary key (RECORDID));
create table TPA_TVMControlDefinition_t (RECORDID NUMBER(19) not null, VERSIONNUMBER NUMBER(19), nodeNo NUMBER(19), SingleFileMaxDeals NUMBER(10), MaxAmountOfBuyTicket NUMBER(19), MaxIdleToCancelDeal NUMBER(19), MaxAmountOfCoinChange NUMBER(19), MaxAmountOfNoteChange NUMBER(19), MaxMoneyOfChangeMoney NUMBER(10), AlmostFullLimitOfCallbackCoinB NUMBER(19), FullLimitOfCallbackCoinBox NUMBER(19), AlmostEmptyLimitOfReturnCoinBo NUMBER(19), EmptyLimitOfReturnCoinBox NUMBER(19), AlmostFullLimitOfCallbackBillB NUMBER(19), FullLimitOfCallbackBillBox NUMBER(19), AlmostEmptyLimitOfReturnBillBo NUMBER(19), EmptyLimitOfReturnBillBox NUMBER(19), MinWarnOfTicketBox NUMBER(5), MaxWarnOfInvalidTicketBox NUMBER(5), primary key (RECORDID));
create table TPA_TVMGUI_t (RECORDID NUMBER(19) not null, VERSIONNUMBER NUMBER(19), nodeNo NUMBER(19), TvmGuiId NUMBER(5), ReducePictureWidth NUMBER(10), ReducePictureHeight NUMBER(10), ADPlayType NUMBER(10), MaxIdleToPlayAD NUMBER(19), PauseDisplayPicture_id NUMBER(19), RunningStatusDisplayWindow_id NUMBER(19), CNLineZonePicture_id NUMBER(19), NowStationDisplayWindow_id NUMBER(19), PayInterfaceDisplayWindow_id NUMBER(19), ENPayInterfacePicture_id NUMBER(19), PauseDisplayWindow_id NUMBER(19), ScreenSize_id NUMBER(19), AddValueDisplayWindow_id NUMBER(19), CNPayInterfacePicture_id NUMBER(19), StartupDisplayWindow_id NUMBER(19), ENLineZonePicture_id NUMBER(19), CheckCardDisplayWindow_id NUMBER(19), LanguageDisplayWindow_id NUMBER(19), BackDisplayWindow_id NUMBER(19), NowtimeDisplayWindow_id NUMBER(19), LineZoneDisplayWindow_id NUMBER(19), StartupDisplayPicture_id NUMBER(19), TPA_EOD_TVM_GUIParam_t_id NUMBER(19), index_col NUMBER(10), primary key (RECORDID));
create table TPA_TicketDefinition_t (RECORDID NUMBER(19) not null, VERSIONNUMBER NUMBER(19), nodeNo NUMBER(19), TicketType varchar2(255), TicketTypeCNName varchar2(255), TicketTypeENName varchar2(255), TicketFamilyType NUMBER(10), AreaTicketFlag NUMBER(5), SaleFixedPrice NUMBER(10), SouvenirFlag NUMBER(10), MemberTicketFlag NUMBER(10), SoundDisplayID NUMBER(5), ConcessionalLampID NUMBER(5), AddValueAuthorized NUMBER(10), MaxAddValue NUMBER(10), DefaultAddValue NUMBER(10), MinAddValue NUMBER(10), MaxRemainingValue NUMBER(10), MinEntryAmount NUMBER(10), MinExitAmount NUMBER(10), DepositValue NUMBER(10), DepreciationValue NUMBER(10), DepreciationCyc NUMBER(5), RefundAuthorized NUMBER(5), MaxImmediateRefundAmount NUMBER(10), RefundCharge NUMBER(10), MaxRideNumber NUMBER(19), DayMaxRideNumber NUMBER(19), DurationMode NUMBER(10), Duration NUMBER(10), FixedEndDate timestamp, ExtendAuthorized NUMBER(10), DefaultExtendDays NUMBER(10), PullInAuthorized NUMBER(10), PeriodofFreeAdjustForNoExit NUMBER(19), OverstayingFeeValue NUMBER(10), OverstayingMode NUMBER(5), NoExitFeeValue NUMBER(10), SurchargeStationMisMatch NUMBER(10), AGMSoundMinBalance NUMBER(10), SaleInitAmount NUMBER(10), SaleInitRideNumber NUMBER(19), EveryTimeAmount NUMBER(10), ConcessionType NUMBER(10), JoinConcessionID varchar2(255), PileConcessionID varchar2(255), EnableFlag NUMBER(10), TPA_EOD_TicketParam_t_id NUMBER(19), index_col NUMBER(10), primary key (RECORDID));
create table TPA_TicketTypeMap_t (RECORDID NUMBER(19) not null, VERSIONNUMBER NUMBER(19), nodeNo NUMBER(19), TicketType varchar2(255), YKTTicketType varchar2(255), CityCode varchar2(255), IssuerCode varchar2(255), ChipType NUMBER(10), TPA_EOD_TicketParam_t_id NUMBER(19), index_col NUMBER(10), primary key (RECORDID));
create table TPA_TimeInterval_t (RECORDID NUMBER(19) not null, VERSIONNUMBER NUMBER(19), nodeNo NUMBER(19), TimeIntervalID NUMBER(5), TimeIntervalValue NUMBER(19), TPA_EOD_CalendarParam_t_id NUMBER(19), index_col NUMBER(10), primary key (RECORDID));
create table TPA_TopBoard_t (RECORDID NUMBER(19) not null, VERSIONNUMBER NUMBER(19), nodeNo NUMBER(19), TopBoardID NUMBER(5), CNDisplay varchar2(255), ENDisplay varchar2(255), TPA_EOD_ISMParam_t_id NUMBER(19), index_col NUMBER(10), TPA_TVMGUI_t_id NUMBER(19), primary key (RECORDID));
create table TPA_TransferStationList_t (RECORDID NUMBER(19) not null, VERSIONNUMBER NUMBER(19), nodeNo NUMBER(19), StationID varchar2(255), EnableFlag NUMBER(10), TPA_TransferStation_t_id NUMBER(19), index_col NUMBER(10), primary key (RECORDID));
create table TPA_TransferStation_t (RECORDID NUMBER(19) not null, VERSIONNUMBER NUMBER(19), nodeNo NUMBER(19), TransferStationID varchar2(255), TransferStationCNName varchar2(255), TransferStationENName varchar2(255), TPA_EOD_NetworkTopologyPara_id NUMBER(19), index_col NUMBER(10), primary key (RECORDID));
create table TPA_ValidBillTypes (TPA_TVMControlDefinition_t_id NUMBER(19) not null, ValidBillTypes NUMBER(10), index_col NUMBER(10) not null, primary key (TPA_TVMControlDefinition_t_id, index_col));
create table TPA_ValidCoinTypes (TPA_TVMControlDefinition_t_id NUMBER(19) not null, ValidCoinTypes NUMBER(10), index_col NUMBER(10) not null, primary key (TPA_TVMControlDefinition_t_id, index_col));
alter table TPA_ADItem_t add constraint FKA452605688FEE9F foreign key (TPA_EOD_ISMParam_t_id) references TPA_EOD_ISMParam_t on delete cascade;
alter table TPA_ADItem_t add constraint FKA4526051E86EA9F foreign key (TPA_TVMGUI_t_id) references TPA_TVMGUI_t on delete cascade;
alter table TPA_AddValueBtn_t add constraint FK40590A4713E388C foreign key (AddValueBtnDisplay_id) references TPA_DisplayWindow_t on delete cascade;
alter table TPA_AddValueBtn_t add constraint FK40590A47688FEE9F foreign key (TPA_EOD_ISMParam_t_id) references TPA_EOD_ISMParam_t on delete cascade;
alter table TPA_AddValueBtn_t add constraint FK40590A471E86EA9F foreign key (TPA_TVMGUI_t_id) references TPA_TVMGUI_t on delete cascade;
alter table TPA_BaseFare_t add constraint FK98AC22EEA443455 foreign key (TPA_EOD_FareParam_t_id) references TPA_EOD_FareParam_t on delete cascade;
alter table TPA_ChipDefinition_t add constraint FKB5E402CE410B7E55 foreign key (TPA_EOD_TicketParam_t_id) references TPA_EOD_TicketParam_t on delete cascade;
alter table TPA_ConcessionalLampType_t add constraint FKF42378502A33D1F foreign key (TPA_EOD_AGMParam_t_id) references TPA_EOD_AGMParam_t on delete cascade;
alter table TPA_EOD_AGMParam_t add constraint FKB2F5C11A5281634E foreign key (IntervalOfMakeFile_id) references TPA_IntervalOfMakeFile_t on delete cascade;
alter table TPA_EOD_AGMParam_t add constraint FKB2F5C11A8CA67B8E foreign key (AGMControlDefinition_id) references TPA_AGMControlDefinition_t on delete cascade;
alter table TPA_EOD_BOMParam_t add constraint FK4962AA415281634E foreign key (IntervalOfMakeFile_id) references TPA_IntervalOfMakeFile_t on delete cascade;
alter table TPA_EOD_BOMParam_t add constraint FK4962AA41F653506E foreign key (BOMControlDefinition_id) references TPA_BOMControlDefinition_t on delete cascade;
alter table TPA_EOD_FareParam_t add constraint FKB7AA1235AE931370 foreign key (BankAddingValuePara_id) references TPA_BankAddingValuePara_t on delete cascade;
alter table TPA_EOD_ISMParam_t add constraint FK48767E1EB7D281CE foreign key (NowStationDisplayWindow_id) references TPA_DisplayWindow_t on delete cascade;
alter table TPA_EOD_ISMParam_t add constraint FK48767E1EBA938CAD foreign key (StartupDisplayWindow_id) references TPA_DisplayWindow_t on delete cascade;
alter table TPA_EOD_ISMParam_t add constraint FK48767E1E1939E0D3 foreign key (NowtimeDisplayWindow_id) references TPA_DisplayWindow_t on delete cascade;
alter table TPA_EOD_ISMParam_t add constraint FK48767E1E9A245E26 foreign key (PauseDisplayWindow_id) references TPA_DisplayWindow_t on delete cascade;
alter table TPA_EOD_ISMParam_t add constraint FK48767E1EFBBCCD3F foreign key (StartupDisplayPicture_id) references TPA_ResourceFile_t on delete cascade;
alter table TPA_EOD_ISMParam_t add constraint FK48767E1ECE785048 foreign key (CheckCardDisplayWindow_id) references TPA_DisplayWindow_t on delete cascade;
alter table TPA_EOD_ISMParam_t add constraint FK48767E1E66CDFEEE foreign key (ScreenSize_id) references TPA_ScreenSize_t on delete cascade;
alter table TPA_EOD_ISMParam_t add constraint FK48767E1E9B213CA1 foreign key (RunningStatusDisplayWindow_id) references TPA_DisplayWindow_t on delete cascade;
alter table TPA_EOD_ISMParam_t add constraint FK48767E1E5281634E foreign key (IntervalOfMakeFile_id) references TPA_IntervalOfMakeFile_t on delete cascade;
alter table TPA_EOD_ISMParam_t add constraint FK48767E1E27F2F1D9 foreign key (TSMControlDefinition_id) references TPA_ISMControlDefinition_t on delete cascade;
alter table TPA_EOD_ISMParam_t add constraint FK48767E1EE462AE6 foreign key (PauseDisplayPicture_id) references TPA_ResourceFile_t on delete cascade;
alter table TPA_EOD_ISMParam_t add constraint FK48767E1ED1A9610A foreign key (InfoQueryDisplayWindow_id) references TPA_DisplayWindow_t on delete cascade;
alter table TPA_EOD_ISMParam_t add constraint FK48767E1E342BC788 foreign key (LanguageDisplayWindow_id) references TPA_DisplayWindow_t on delete cascade;
alter table TPA_EOD_ISMParam_t add constraint FK48767E1E381459A0 foreign key (AddValueDisplayWindow_id) references TPA_DisplayWindow_t on delete cascade;
alter table TPA_EOD_PCAParam_t add constraint FKD3A38B735281634E foreign key (IntervalOfMakeFile_id) references TPA_IntervalOfMakeFile_t on delete cascade;
alter table TPA_EOD_PCAParam_t add constraint FKD3A38B7382816AE foreign key (PCAControlDefinition_id) references TPA_PCAControlDefinition_t on delete cascade;
alter table TPA_EOD_RGParam_t add constraint FKF5C506AE18C40275 foreign key (TPA_EOD_RGParamList_t_id) references TPA_EOD_RGParamList_t on delete cascade;
alter table TPA_EOD_SLESoftParam_t add constraint FKCFB84B6CE66B6E foreign key (BOMSoft_id) references TPA_ResourceFile_t on delete cascade;
alter table TPA_EOD_SLESoftParam_t add constraint FKCFB84BF7274CA0 foreign key (PCASoft_id) references TPA_ResourceFile_t on delete cascade;
alter table TPA_EOD_SLESoftParam_t add constraint FKCFB84BA7EF68A3 foreign key (TVMSoft_id) references TPA_ResourceFile_t on delete cascade;
alter table TPA_EOD_SLESoftParam_t add constraint FKCFB84B6BFA3F4B foreign key (ISMSoft_id) references TPA_ResourceFile_t on delete cascade;
alter table TPA_EOD_SLESoftParam_t add constraint FKCFB84BD6798247 foreign key (AGMSoft_id) references TPA_ResourceFile_t on delete cascade;
alter table TPA_EOD_SystemParam_t add constraint FK31CE28D460D2A12E foreign key (DeviceLoginParam_id) references TPA_DeviceLoginParam_t on delete cascade;
alter table TPA_EOD_SystemParam_t add constraint FK31CE28D4C942FB2E foreign key (SCUploadFile_id) references TPA_SCUploadFile_t on delete cascade;
alter table TPA_EOD_SystemParam_t add constraint FK31CE28D4D2BBF4F0 foreign key (SysTimeSync_id) references TPA_SysTimeSync_t on delete cascade;
alter table TPA_EOD_TPSoftParam_t add constraint FKEE44CE7D5C2CF32 foreign key (TPSoft_id) references TPA_ResourceFile_t on delete cascade;
alter table TPA_EOD_TVMParam_t add constraint FK846BA7765281634E foreign key (IntervalOfMakeFile_id) references TPA_IntervalOfMakeFile_t on delete cascade;
alter table TPA_EOD_TVMParam_t add constraint FK846BA776A90E070E foreign key (TVMControlDefinition_id) references TPA_TVMControlDefinition_t on delete cascade;
alter table TPA_ExpressBtnForBOM_t add constraint FK51FC6CB2C52057BF foreign key (TPA_EOD_BOMParam_t_id) references TPA_EOD_BOMParam_t on delete cascade;
alter table TPA_ExpressBtn_t add constraint FK4066FA9B13890336 foreign key (BuyBtnDisplay_id) references TPA_DisplayWindow_t on delete cascade;
alter table TPA_ExpressBtn_t add constraint FK4066FA9B1E86EA9F foreign key (TPA_TVMGUI_t_id) references TPA_TVMGUI_t on delete cascade;
alter table TPA_FareGroup_t add constraint FK38E1BA8CEA443455 foreign key (TPA_EOD_FareParam_t_id) references TPA_EOD_FareParam_t on delete cascade;
alter table TPA_FareTierMatrix_t add constraint FK9CD3B6A0EA443455 foreign key (TPA_EOD_FareParam_t_id) references TPA_EOD_FareParam_t on delete cascade;
alter table TPA_FareTierTimeTable_t add constraint FK395394C3ECEF8D5 foreign key (TPA_EOD_CalendarParam_t_id) references TPA_EOD_CalendarParam_t on delete cascade;
alter table TPA_JoinConcessionDefinition_t add constraint FKD3F4D690341963D5 foreign key (TPA_EOD_ConcessionParam_t_id) references TPA_EOD_ConcessionParam_t on delete cascade;
alter table TPA_LineBtn_t add constraint FK2A9FE92344FC57B7 foreign key (ENLinePicture_id) references TPA_ResourceFile_t on delete cascade;
alter table TPA_LineBtn_t add constraint FK2A9FE9234B884B94 foreign key (LineDisplay_id) references TPA_DisplayWindow_t on delete cascade;
alter table TPA_LineBtn_t add constraint FK2A9FE92381D89BF9 foreign key (CNLinePicture_id) references TPA_ResourceFile_t on delete cascade;
alter table TPA_LineBtn_t add constraint FK2A9FE9232BDC1488 foreign key (LineBtnDisplay_id) references TPA_DisplayWindow_t on delete cascade;
alter table TPA_LineBtn_t add constraint FK2A9FE9231E86EA9F foreign key (TPA_TVMGUI_t_id) references TPA_TVMGUI_t on delete cascade;
alter table TPA_Line_t add constraint FK6C3AB435DEF42A5 foreign key (TPA_EOD_NetworkTopologyPara_id) references TPA_EOD_NetworkTopologyParam_t on delete cascade;
alter table TPA_NumbersBtn_t add constraint FK70EE34017906B1F2 foreign key (NumbersBtnDisplay_id) references TPA_DisplayWindow_t on delete cascade;
alter table TPA_NumbersBtn_t add constraint FK70EE34011E86EA9F foreign key (TPA_TVMGUI_t_id) references TPA_TVMGUI_t on delete cascade;
alter table TPA_PassageModeInfo_t add constraint FK206D85FA26A70895 foreign key (TPA_EOD_RGParam_t_id) references TPA_EOD_RGParam_t on delete cascade;
alter table TPA_PayInterfacePosition_t add constraint FK4505C389B3BFD5F4 foreign key (PosDisplay_id) references TPA_DisplayWindow_t on delete cascade;
alter table TPA_PayInterfacePosition_t add constraint FK4505C3891E86EA9F foreign key (TPA_TVMGUI_t_id) references TPA_TVMGUI_t on delete cascade;
alter table TPA_PileConcessionDefinition_t add constraint FK1E314498341963D5 foreign key (TPA_EOD_ConcessionParam_t_id) references TPA_EOD_ConcessionParam_t on delete cascade;
alter table TPA_SoundDisplay_t add constraint FK6A7B36422A33D1F foreign key (TPA_EOD_AGMParam_t_id) references TPA_EOD_AGMParam_t on delete cascade;
alter table TPA_SpecialDate_t add constraint FK7745F0A23ECEF8D5 foreign key (TPA_EOD_CalendarParam_t_id) references TPA_EOD_CalendarParam_t on delete cascade;
alter table TPA_StationBtnInLineZone_t add constraint FKE03441BC9BB7B59 foreign key (StationInLineZoneDisplay_id) references TPA_DisplayWindow_t on delete cascade;
alter table TPA_StationBtnInLineZone_t add constraint FKE03441BC1E86EA9F foreign key (TPA_TVMGUI_t_id) references TPA_TVMGUI_t on delete cascade;
alter table TPA_StationBtnInLine_t add constraint FKB6862270AFEF0D2D foreign key (StationInLineDisplay_id) references TPA_DisplayWindow_t on delete cascade;
alter table TPA_StationBtnInLine_t add constraint FKB68622701E86EA9F foreign key (TPA_TVMGUI_t_id) references TPA_TVMGUI_t on delete cascade;
alter table TPA_Station_t add constraint FK1B36DD8F5DEF42A5 foreign key (TPA_EOD_NetworkTopologyPara_id) references TPA_EOD_NetworkTopologyParam_t on delete cascade;
alter table TPA_TVMGUI_t add constraint FK7C7D18DFB7D281CE foreign key (NowStationDisplayWindow_id) references TPA_DisplayWindow_t on delete cascade;
alter table TPA_TVMGUI_t add constraint FK7C7D18DF60E90814 foreign key (ENPayInterfacePicture_id) references TPA_ResourceFile_t on delete cascade;
alter table TPA_TVMGUI_t add constraint FK7C7D18DFBA938CAD foreign key (StartupDisplayWindow_id) references TPA_DisplayWindow_t on delete cascade;
alter table TPA_TVMGUI_t add constraint FK7C7D18DF3AB9BC1 foreign key (PayInterfaceDisplayWindow_id) references TPA_DisplayWindow_t on delete cascade;
alter table TPA_TVMGUI_t add constraint FK7C7D18DF1939E0D3 foreign key (NowtimeDisplayWindow_id) references TPA_DisplayWindow_t on delete cascade;
alter table TPA_TVMGUI_t add constraint FK7C7D18DFC0E09DE3 foreign key (ENLineZonePicture_id) references TPA_ResourceFile_t on delete cascade;
alter table TPA_TVMGUI_t add constraint FK7C7D18DF9A245E26 foreign key (PauseDisplayWindow_id) references TPA_DisplayWindow_t on delete cascade;
alter table TPA_TVMGUI_t add constraint FK7C7D18DF68E5EA56 foreign key (CNPayInterfacePicture_id) references TPA_ResourceFile_t on delete cascade;
alter table TPA_TVMGUI_t add constraint FK7C7D18DFCE785048 foreign key (CheckCardDisplayWindow_id) references TPA_DisplayWindow_t on delete cascade;
alter table TPA_TVMGUI_t add constraint FK7C7D18DFFBBCCD3F foreign key (StartupDisplayPicture_id) references TPA_ResourceFile_t on delete cascade;
alter table TPA_TVMGUI_t add constraint FK7C7D18DF66CDFEEE foreign key (ScreenSize_id) references TPA_ScreenSize_t on delete cascade;
alter table TPA_TVMGUI_t add constraint FK7C7D18DF9B213CA1 foreign key (RunningStatusDisplayWindow_id) references TPA_DisplayWindow_t on delete cascade;
alter table TPA_TVMGUI_t add constraint FK7C7D18DFF19CF125 foreign key (CNLineZonePicture_id) references TPA_ResourceFile_t on delete cascade;
alter table TPA_TVMGUI_t add constraint FK7C7D18DF88683B17 foreign key (BackDisplayWindow_id) references TPA_DisplayWindow_t on delete cascade;
alter table TPA_TVMGUI_t add constraint FK7C7D18DF91FE5DD0 foreign key (LineZoneDisplayWindow_id) references TPA_DisplayWindow_t on delete cascade;
alter table TPA_TVMGUI_t add constraint FK7C7D18DFA9FBD6BF foreign key (TPA_EOD_TVM_GUIParam_t_id) references TPA_EOD_TVM_GUIParam_t on delete cascade;
alter table TPA_TVMGUI_t add constraint FK7C7D18DFE462AE6 foreign key (PauseDisplayPicture_id) references TPA_ResourceFile_t on delete cascade;
alter table TPA_TVMGUI_t add constraint FK7C7D18DF381459A0 foreign key (AddValueDisplayWindow_id) references TPA_DisplayWindow_t on delete cascade;
alter table TPA_TVMGUI_t add constraint FK7C7D18DF342BC788 foreign key (LanguageDisplayWindow_id) references TPA_DisplayWindow_t on delete cascade;
alter table TPA_TicketDefinition_t add constraint FKD5642B0E410B7E55 foreign key (TPA_EOD_TicketParam_t_id) references TPA_EOD_TicketParam_t on delete cascade;
alter table TPA_TicketTypeMap_t add constraint FKB2864A71410B7E55 foreign key (TPA_EOD_TicketParam_t_id) references TPA_EOD_TicketParam_t on delete cascade;
alter table TPA_TimeInterval_t add constraint FK6136C8813ECEF8D5 foreign key (TPA_EOD_CalendarParam_t_id) references TPA_EOD_CalendarParam_t on delete cascade;
alter table TPA_TopBoard_t add constraint FK254BD5A0688FEE9F foreign key (TPA_EOD_ISMParam_t_id) references TPA_EOD_ISMParam_t on delete cascade;
alter table TPA_TopBoard_t add constraint FK254BD5A01E86EA9F foreign key (TPA_TVMGUI_t_id) references TPA_TVMGUI_t on delete cascade;
alter table TPA_TransferStationList_t add constraint FKBE0895A23291A755 foreign key (TPA_TransferStation_t_id) references TPA_TransferStation_t on delete cascade;
alter table TPA_TransferStation_t add constraint FK6B4037E45DEF42A5 foreign key (TPA_EOD_NetworkTopologyPara_id) references TPA_EOD_NetworkTopologyParam_t on delete cascade;
alter table TPA_ValidBillTypes add constraint FK34449E7088A2CDDF foreign key (TPA_TVMControlDefinition_t_id) references TPA_TVMControlDefinition_t on delete cascade;
alter table TPA_ValidCoinTypes add constraint FK9C871A2688A2CDDF foreign key (TPA_TVMControlDefinition_t_id) references TPA_TVMControlDefinition_t on delete cascade;
create sequence S_TPA_ADItem_t minvalue 1 maxvalue 999999999999999999999999999 start with 1 increment by 1 cache 20;
create sequence S_TPA_AGMControlDefinition_t minvalue 1 maxvalue 999999999999999999999999999 start with 1 increment by 1 cache 20;
create sequence S_TPA_AddValueBtn_t minvalue 1 maxvalue 999999999999999999999999999 start with 1 increment by 1 cache 20;
create sequence S_TPA_BOMControlDefinition_t minvalue 1 maxvalue 999999999999999999999999999 start with 1 increment by 1 cache 20;
create sequence S_TPA_BankAddingValuePara_t minvalue 1 maxvalue 999999999999999999999999999 start with 1 increment by 1 cache 20;
create sequence S_TPA_BaseFare_t minvalue 1 maxvalue 999999999999999999999999999 start with 1 increment by 1 cache 20;
create sequence S_TPA_ChipDefinition_t minvalue 1 maxvalue 999999999999999999999999999 start with 1 increment by 1 cache 20;
create sequence S_TPA_ConcessionalLampType_t minvalue 1 maxvalue 999999999999999999999999999 start with 1 increment by 1 cache 20;
create sequence S_TPA_DeviceLoginParam_t minvalue 1 maxvalue 999999999999999999999999999 start with 1 increment by 1 cache 20;
create sequence S_TPA_DisplayWindow_t minvalue 1 maxvalue 999999999999999999999999999 start with 1 increment by 1 cache 20;
create sequence S_TPA_EOD_AGMParam_t minvalue 1 maxvalue 999999999999999999999999999 start with 1 increment by 1 cache 20;
create sequence S_TPA_EOD_BOMParam_t minvalue 1 maxvalue 999999999999999999999999999 start with 1 increment by 1 cache 20;
create sequence S_TPA_EOD_CalendarParam_t minvalue 1 maxvalue 999999999999999999999999999 start with 1 increment by 1 cache 20;
create sequence S_TPA_EOD_ConcessionParam_t minvalue 1 maxvalue 999999999999999999999999999 start with 1 increment by 1 cache 20;
create sequence S_TPA_EOD_FareParam_t minvalue 1 maxvalue 999999999999999999999999999 start with 1 increment by 1 cache 20;
create sequence S_TPA_EOD_ISMParam_t minvalue 1 maxvalue 999999999999999999999999999 start with 1 increment by 1 cache 20;
create sequence S_TPA_EOD_NetworkTopologyParam minvalue 1 maxvalue 999999999999999999999999999 start with 1 increment by 1 cache 20;
create sequence S_TPA_EOD_PCAParam_t minvalue 1 maxvalue 999999999999999999999999999 start with 1 increment by 1 cache 20;
create sequence S_TPA_EOD_RGParamList_t minvalue 1 maxvalue 999999999999999999999999999 start with 1 increment by 1 cache 20;
create sequence S_TPA_EOD_RGParam_t minvalue 1 maxvalue 999999999999999999999999999 start with 1 increment by 1 cache 20;
create sequence S_TPA_EOD_SLESoftParam_t minvalue 1 maxvalue 999999999999999999999999999 start with 1 increment by 1 cache 20;
create sequence S_TPA_EOD_SystemParam_t minvalue 1 maxvalue 999999999999999999999999999 start with 1 increment by 1 cache 20;
create sequence S_TPA_EOD_TPSoftParam_t minvalue 1 maxvalue 999999999999999999999999999 start with 1 increment by 1 cache 20;
create sequence S_TPA_EOD_TVMParam_t minvalue 1 maxvalue 999999999999999999999999999 start with 1 increment by 1 cache 20;
create sequence S_TPA_EOD_TVM_GUIParam_t minvalue 1 maxvalue 999999999999999999999999999 start with 1 increment by 1 cache 20;
create sequence S_TPA_EOD_TicketParam_t minvalue 1 maxvalue 999999999999999999999999999 start with 1 increment by 1 cache 20;
create sequence S_TPA_ExpressBtnForBOM_t minvalue 1 maxvalue 999999999999999999999999999 start with 1 increment by 1 cache 20;
create sequence S_TPA_ExpressBtn_t minvalue 1 maxvalue 999999999999999999999999999 start with 1 increment by 1 cache 20;
create sequence S_TPA_FareGroup_t minvalue 1 maxvalue 999999999999999999999999999 start with 1 increment by 1 cache 20;
create sequence S_TPA_FareTierMatrix_t minvalue 1 maxvalue 999999999999999999999999999 start with 1 increment by 1 cache 20;
create sequence S_TPA_FareTierTimeTable_t minvalue 1 maxvalue 999999999999999999999999999 start with 1 increment by 1 cache 20;
create sequence S_TPA_ISMControlDefinition_t minvalue 1 maxvalue 999999999999999999999999999 start with 1 increment by 1 cache 20;
create sequence S_TPA_IntervalOfMakeFile_t minvalue 1 maxvalue 999999999999999999999999999 start with 1 increment by 1 cache 20;
create sequence S_TPA_JoinConcessionDefinition minvalue 1 maxvalue 999999999999999999999999999 start with 1 increment by 1 cache 20;
create sequence S_TPA_LineBtn_t minvalue 1 maxvalue 999999999999999999999999999 start with 1 increment by 1 cache 20;
create sequence S_TPA_Line_t minvalue 1 maxvalue 999999999999999999999999999 start with 1 increment by 1 cache 20;
create sequence S_TPA_NumbersBtn_t minvalue 1 maxvalue 999999999999999999999999999 start with 1 increment by 1 cache 20;
create sequence S_TPA_PCAControlDefinition_t minvalue 1 maxvalue 999999999999999999999999999 start with 1 increment by 1 cache 20;
create sequence S_TPA_PassageModeInfo_t minvalue 1 maxvalue 999999999999999999999999999 start with 1 increment by 1 cache 20;
create sequence S_TPA_PayInterfacePosition_t minvalue 1 maxvalue 999999999999999999999999999 start with 1 increment by 1 cache 20;
create sequence S_TPA_PileConcessionDefinition minvalue 1 maxvalue 999999999999999999999999999 start with 1 increment by 1 cache 20;
create sequence S_TPA_ResourceFile_t minvalue 1 maxvalue 999999999999999999999999999 start with 1 increment by 1 cache 20;
create sequence S_TPA_SCUploadFile_t minvalue 1 maxvalue 999999999999999999999999999 start with 1 increment by 1 cache 20;
create sequence S_TPA_ScreenSize_t minvalue 1 maxvalue 999999999999999999999999999 start with 1 increment by 1 cache 20;
create sequence S_TPA_SoundDisplay_t minvalue 1 maxvalue 999999999999999999999999999 start with 1 increment by 1 cache 20;
create sequence S_TPA_SpecialDate_t minvalue 1 maxvalue 999999999999999999999999999 start with 1 increment by 1 cache 20;
create sequence S_TPA_StationBtnInLineZone_t minvalue 1 maxvalue 999999999999999999999999999 start with 1 increment by 1 cache 20;
create sequence S_TPA_StationBtnInLine_t minvalue 1 maxvalue 999999999999999999999999999 start with 1 increment by 1 cache 20;
create sequence S_TPA_Station_t minvalue 1 maxvalue 999999999999999999999999999 start with 1 increment by 1 cache 20;
create sequence S_TPA_SysTimeSync_t minvalue 1 maxvalue 999999999999999999999999999 start with 1 increment by 1 cache 20;
create sequence S_TPA_TVMControlDefinition_t minvalue 1 maxvalue 999999999999999999999999999 start with 1 increment by 1 cache 20;
create sequence S_TPA_TVMGUI_t minvalue 1 maxvalue 999999999999999999999999999 start with 1 increment by 1 cache 20;
create sequence S_TPA_TicketDefinition_t minvalue 1 maxvalue 999999999999999999999999999 start with 1 increment by 1 cache 20;
create sequence S_TPA_TicketTypeMap_t minvalue 1 maxvalue 999999999999999999999999999 start with 1 increment by 1 cache 20;
create sequence S_TPA_TimeInterval_t minvalue 1 maxvalue 999999999999999999999999999 start with 1 increment by 1 cache 20;
create sequence S_TPA_TopBoard_t minvalue 1 maxvalue 999999999999999999999999999 start with 1 increment by 1 cache 20;
create sequence S_TPA_TransferStationList_t minvalue 1 maxvalue 999999999999999999999999999 start with 1 increment by 1 cache 20;
create sequence S_TPA_TransferStation_t minvalue 1 maxvalue 999999999999999999999999999 start with 1 increment by 1 cache 20;
comment on column TPA_FareTierMatrix_t.FareTier is ' 费率等级代码 (BCD)';
comment on column TPA_FareTierMatrix_t.StationIDIn is ' 进站车站编号(BCD) ';
comment on column TPA_FareTierMatrix_t.StationIDOut is ' 出站车站编号(BCD)';
comment on column TPA_TransferStation_t.TransferStationID is ' 换乘区域代码 (BCD)';
comment on column TPA_TransferStation_t.TransferStationCNName is ' 换乘区域中文名称 ';
comment on column TPA_TransferStation_t.TransferStationENName is ' 换乘区域英文简称 ';
--comment on column TPA_TransferStation_t.TransferStationLists is ' 换乘区域内车站列表 ';
comment on column TPA_IntervalOfMakeFile_t.IntervalOfBuildYPTUDFile is ' 一票通交易数据文件生成时间间隔 ';
comment on column TPA_IntervalOfMakeFile_t.IntervalOfBuildYKTUDFile is ' 一卡通交易数据文件生成时间间隔 ';
comment on column TPA_IntervalOfMakeFile_t.IntervalOfBuildARFile is ' 审计数据文件生成时间间隔 ';
comment on column TPA_EOD_SLESoftParam_t.TVMSoft_id is ' TVM软件文件 ';
comment on column TPA_EOD_SLESoftParam_t.BOMSoft_id is ' BOM软件文件 ';
comment on column TPA_EOD_SLESoftParam_t.AGMSoft_id is ' AGM软件文件 ';
comment on column TPA_EOD_SLESoftParam_t.ISMSoft_id is ' ISM软件文件 ';
comment on column TPA_EOD_SLESoftParam_t.PCASoft_id is ' PCA软件文件 ';
comment on column TPA_EOD_ISMParam_t.TSMControlDefinition_id is ' ISM的控制参数 ';
comment on column TPA_EOD_ISMParam_t.IntervalOfMakeFile_id is ' 文件生成时间间隔 ';
comment on column TPA_EOD_ISMParam_t.ScreenSize_id is ' 屏幕尺寸 ';
comment on column TPA_EOD_ISMParam_t.StartupDisplayPicture_id is ' 启动窗口图片文件 ';
comment on column TPA_EOD_ISMParam_t.StartupDisplayWindow_id is ' 启动窗口图片显示坐标 ';
comment on column TPA_EOD_ISMParam_t.PauseDisplayPicture_id is ' 暂停服务窗口图片文件 ';
comment on column TPA_EOD_ISMParam_t.PauseDisplayWindow_id is ' 暂停服务窗口图片显示坐标 ';
comment on column TPA_EOD_ISMParam_t.NowtimeDisplayWindow_id is ' 当前日期时间显示坐标 ';
comment on column TPA_EOD_ISMParam_t.NowStationDisplayWindow_id is ' 当前车站显示坐标 ';
comment on column TPA_EOD_ISMParam_t.RunningStatusDisplayWindow_id is ' 运行状态显示坐标 ';
--comment on column TPA_EOD_ISMParam_t.ADItems is ' 广告列表（预留） ';
comment on column TPA_EOD_ISMParam_t.ADPlayType is ' 广告播放方式 0从头开始，1继续播放（预留） ';
comment on column TPA_EOD_ISMParam_t.MaxIdleToPlayAD is ' 进入广告模式的最大空闲时间（预留） ';
--comment on column TPA_EOD_ISMParam_t.TopBoards is ' 顶板列表 ';
comment on column TPA_EOD_ISMParam_t.LanguageDisplayWindow_id is '中英文按钮显示信息';
comment on column TPA_EOD_ISMParam_t.CheckCardDisplayWindow_id is '验卡按钮显示信息 ';
comment on column TPA_EOD_ISMParam_t.InfoQueryDisplayWindow_id is '信息查询按钮显示信息';
comment on column TPA_EOD_ISMParam_t.AddValueDisplayWindow_id is ' 充值按钮显示坐标 ';
--comment on column TPA_EOD_ISMParam_t.AddValueBtns is ' 充值选择按钮列表 ';
comment on column TPA_SysTimeSync_t.TimeDeviationPeriod is ' 时间同步校准间隔 ';
comment on column TPA_SysTimeSync_t.MinTimeDeviation is ' 时钟同步最小阀值 ';
comment on column TPA_SysTimeSync_t.WarnTimeDeviation is ' 时钟同步警告阀值 ';
comment on column TPA_SysTimeSync_t.MaxTimeDeviation is ' 时间同步最大阀值 ';
comment on column TPA_PayInterfacePosition_t.PosType is ' 位置类型 ';
comment on column TPA_PayInterfacePosition_t.PosDisplay_id is ' 位置坐标信息 ';
comment on column TPA_ADItem_t.ADItemID is ' 广告编号ID ';
comment on column TPA_ADItem_t.ADType is ' 广告类型 ';
comment on column TPA_ADItem_t.ADItemFileName is ' 广告多媒体播放文件名称 ';
comment on column TPA_ADItem_t.ADItemFileMD5 is ' 广告多媒体播放文件整个文件二进制内容的MD5码 ';
--comment on column TPA_EOD_NetworkTopologyParam_t.Lines is ' 线路列表 ';
--comment on column TPA_EOD_NetworkTopologyParam_t.Stations is ' 车站列表 ';
--comment on column TPA_EOD_NetworkTopologyParam_t.TransferStations is ' 换乘车站列表 ';
comment on column TPA_FareGroup_t.TicketType is ' 车票类型代码 (HEX)';
comment on column TPA_FareGroup_t.DateTypeID is ' 日期类型代码 ';
comment on column TPA_FareGroup_t.TimeIntervalID is ' 时间段代码 ';
comment on column TPA_FareGroup_t.FareGroupID is ' 车票费率组代码(BCD) ';
comment on column TPA_EOD_TPSoftParam_t.TPSoft_id is ' TP软件文件 ';
comment on column TPA_BaseFare_t.FareGroupID is ' 费率组代码(BCD) ';
comment on column TPA_BaseFare_t.FareTier is ' 费率等级代码 (BCD)';
comment on column TPA_BaseFare_t.FareAmount is ' 费率值 ';
comment on column TPA_EOD_SystemParam_t.SysTimeSync_id is ' 时间同步参数 ';
comment on column TPA_EOD_SystemParam_t.SCUploadFile_id is ' SC文件上报参数 ';
comment on column TPA_EOD_SystemParam_t.DeviceLoginParam_id is ' 设备登录参数 ';
comment on column TPA_ChipDefinition_t.ChipType is ' 芯片类型代码 ';
comment on column TPA_ChipDefinition_t.PhycialValidityPeriod is ' 默认芯片物理有效期长度(天) ';
comment on column TPA_ChipDefinition_t.MaxChipIONumber is ' RFU 默认芯片最大交易次数';
comment on column TPA_ISMControlDefinition_t.SingleFileMaxDeals is ' 单个文件最大交易数量 ';
comment on column TPA_ISMControlDefinition_t.MaxIdleToCancelDeal is ' 等待操作最长时间，超出时间则取消操作 ';
comment on column TPA_ISMControlDefinition_t.AlmostFullLimitOfBillBox is ' 纸币钱箱将满报警值 ';
comment on column TPA_ISMControlDefinition_t.FullLimitOfBillBox is ' 纸币钱箱满报警值 ';
comment on column TPA_ISMControlDefinition_t.MaxMoneyOfCashAddValue is ' 现金单次充值最大金额 ';
comment on column TPA_FareTierTimeTable_t.FareTier is ' 费率等级代码 (BCD)';
comment on column TPA_FareTierTimeTable_t.AllowedTravelPeriod is ' 允许站内的逗留时间 ';
comment on column TPA_TimeInterval_t.TimeIntervalID is ' 时间段编号  ';
comment on column TPA_TimeInterval_t.TimeIntervalValue is ' 时间段结束时间 ';
comment on column TPA_StationBtnInLineZone_t.StationID is ' 车站选择按钮ID(BCD) ';
comment on column TPA_StationBtnInLineZone_t.StationInLineZoneDisplay_id is ' 车站选择区域坐标信息 ';
comment on column TPA_StationBtnInLineZone_t.StationSelBtnEnable is ' 车站选择按钮启用标志 ';
comment on column TPA_AGMControlDefinition_t.SingleFileMaxDeals is ' 单个文件最大交易数量 ';
comment on column TPA_AGMControlDefinition_t.MaxIntervalToRejectSameTicket is ' 拒绝同张票卡重复被寻卡最大间隔时间 ';
comment on column TPA_AGMControlDefinition_t.MaxDelayAfterRejectInvalidTick is ' 拒绝非法票卡后的延迟时间 ';
comment on column TPA_AGMControlDefinition_t.MaxWarnOfTicketBox is ' 票箱将满警戒线容量 ';
comment on column TPA_AGMControlDefinition_t.PatronQueue is ' 乘客过闸最大滞留量 ';
comment on column TPA_AGMControlDefinition_t.MaxDelayOfShowPicture is ' 图像显示滞留时间 ';
comment on column TPA_AGMControlDefinition_t.ReaderWorkInGateInbreak is ' 闸机入侵状态时读卡器启动标志(0：停止，1：继续) ';
comment on column TPA_AGMControlDefinition_t.MaxWaitAfterReadCard is ' 乘客刷卡后闸机最大等待时间 ';
comment on column TPA_AGMControlDefinition_t.MaxIntervalOfShutGate is ' 乘客连续通过闸机时，扇门保持打开状态的间隔时间 ';
comment on column TPA_AGMControlDefinition_t.MaxStayInGate is ' 乘客通道内最大滞留时间 ';
comment on column TPA_JoinConcessionDefinition_t.JoinConcessionID is ' 联程优惠代码(BCD) ';
comment on column TPA_JoinConcessionDefinition_t.JoinConcessionIndustryScope is ' 联程优惠换乘范围(BCD) ';
comment on column TPA_JoinConcessionDefinition_t.JoinConcessionValidTime is ' 联程优惠有效时间范围(单位：分钟) ';
comment on column TPA_JoinConcessionDefinition_t.JoinConcessionType is ' 联程优惠方式(0：金额，1：比例) ';
comment on column TPA_JoinConcessionDefinition_t.JoinConcessionAmount is ' 联程优惠金额 ';
comment on column TPA_JoinConcessionDefinition_t.JoinConcessionPercentage is ' 联程优惠比例 ';
comment on column TPA_AddValueBtn_t.AddValueBtnIndex is ' 充值金额按钮ID ';
comment on column TPA_AddValueBtn_t.AddValueBtnValue is ' 充值金额按钮显示金额 ';
comment on column TPA_AddValueBtn_t.AddValueBtnDisplay_id is ' 充值金额按钮显示坐标 ';
comment on column TPA_SoundDisplay_t.SoundDisplayID is ' AGM提示音编号 ';
comment on column TPA_SoundDisplay_t.SoundDisplayFileName is ' AGM提示音文件名 ';
comment on column TPA_SoundDisplay_t.SoundDisplayFileMD5 is ' AGM提示音文件整个文件二进制内容的MD5码 ';
comment on column TPA_BOMControlDefinition_t.SingleFileMaxDeals is ' 单个文件最大交易数量 ';
comment on column TPA_BOMControlDefinition_t.MaxExitNoOperation is ' 最近无操作自动退出最长时间 ';
comment on column TPA_BOMControlDefinition_t.MinWarnAmountOfTicketBox is ' 票箱将空警戒线容量 ';
comment on column TPA_TicketTypeMap_t.TicketType is ' 地铁车票类型代码(HEX) ';
comment on column TPA_TicketTypeMap_t.YKTTicketType is ' 外部票种类型代码(BCD) ';
comment on column TPA_TicketTypeMap_t.CityCode is ' 城市代码(BCD) ';
comment on column TPA_TicketTypeMap_t.IssuerCode is ' 发卡方代码(BCD) ';
comment on column TPA_TicketTypeMap_t.ChipType is ' 芯片类型 ';
comment on column TPA_StationBtnInLine_t.StationID is ' 车站选择按钮ID(BCD) ';
comment on column TPA_StationBtnInLine_t.LineID is ' 线路选择按钮ID(BCD) ';
comment on column TPA_StationBtnInLine_t.StationInLineDisplay_id is ' 车站选择区域坐标信息 ';
comment on column TPA_StationBtnInLine_t.StationSelBtnEnable is ' 车站选择按钮启用标志(0不启用，1启用) ';
comment on column TPA_NumbersBtn_t.BtnIndex is ' 张数按钮ID ';
comment on column TPA_NumbersBtn_t.TicketQuantity is ' 张数按钮显示张数 ';
comment on column TPA_NumbersBtn_t.NumbersBtnDisplay_id is ' 张数按钮显示坐标 ';
comment on column TPA_Line_t.LineID is ' 线路代码 (BCD)';
comment on column TPA_Line_t.LineCNName is ' 线路中文名称 ';
comment on column TPA_Line_t.LineENName is ' 线路英文全称 ';
comment on column TPA_Line_t.EnableFlag is ' 启用标志位 ';
comment on column TPA_TicketDefinition_t.TicketType is ' 车票类型代码(HEX) ';
comment on column TPA_TicketDefinition_t.TicketTypeCNName is ' 车票类型中文名称 ';
comment on column TPA_TicketDefinition_t.TicketTypeENName is ' 车票类型英文简称 ';
comment on column TPA_TicketDefinition_t.TicketFamilyType is ' 票种大类类型代码 ';
comment on column TPA_TicketDefinition_t.AreaTicketFlag is ' 车票使用范围限制标志(0: 无使用范围限制 1: 在限定的范围使用  ';
comment on column TPA_TicketDefinition_t.SaleFixedPrice is ' 固定发售价格 ';
comment on column TPA_TicketDefinition_t.SouvenirFlag is ' 纪念票标志(0: 非纪念票; 1: 纪念票) ';
comment on column TPA_TicketDefinition_t.MemberTicketFlag is ' 记名票标志位(0: 非记名票; 1: 记名票) ';
comment on column TPA_TicketDefinition_t.SoundDisplayID is ' AGM提示音编号 ';
comment on column TPA_TicketDefinition_t.ConcessionalLampID is ' AGM显示灯颜色编号（闪动频率和时常设备由本地控制） ';
comment on column TPA_TicketDefinition_t.AddValueAuthorized is ' 是否可充值(0-否，1-是) ';
comment on column TPA_TicketDefinition_t.MaxAddValue is ' 充值最大金额，自动充值上限 ';
comment on column TPA_TicketDefinition_t.DefaultAddValue is ' 充值起充金额 ';
comment on column TPA_TicketDefinition_t.MinAddValue is ' 充值步长金额 ';
comment on column TPA_TicketDefinition_t.MaxRemainingValue is ' 储值车票最大余额 ';
comment on column TPA_TicketDefinition_t.MinEntryAmount is ' 最小进站金额 ';
comment on column TPA_TicketDefinition_t.MinExitAmount is ' 最小出站金额（预留）';
comment on column TPA_TicketDefinition_t.DepositValue is ' 票卡售卖押金 ';
comment on column TPA_TicketDefinition_t.DepreciationValue is ' 折旧计算参数,固定为每周期扣除的折旧费 ';
comment on column TPA_TicketDefinition_t.DepreciationCyc is ' 折旧计算单位周期  0-按天 1-按月 2按年 ';
comment on column TPA_TicketDefinition_t.RefundAuthorized is ' 退票方式 0：不允许退票，1：只允许售票站退票 2-允许退票 ';
comment on column TPA_TicketDefinition_t.MaxImmediateRefundAmount is ' 最大即时退票金额 ';
comment on column TPA_TicketDefinition_t.RefundCharge is ' 退票手续费 ';
comment on column TPA_TicketDefinition_t.MaxRideNumber is ' 最多乘坐次数(限制计时票) ';
comment on column TPA_TicketDefinition_t.DayMaxRideNumber is ' 单日最多乘坐次数(限制计时票) ';
comment on column TPA_TicketDefinition_t.DurationMode is ' 车票有效期类别 ';
comment on column TPA_TicketDefinition_t.Duration is ' 期限时间段(天) ';
comment on column TPA_TicketDefinition_t.FixedEndDate is ' 固定截至有效日期 ';
comment on column TPA_TicketDefinition_t.ExtendAuthorized is ' 是否允许延期 (0：否，1：是) ';
comment on column TPA_TicketDefinition_t.DefaultExtendDays is ' 默认延期天数 ';
comment on column TPA_TicketDefinition_t.PullInAuthorized is ' 是否只允许售票站进站 (0：否，1：是) ';
comment on column TPA_TicketDefinition_t.PeriodofFreeAdjustForNoExit is ' 重复进站免费更新最大时限 ';
comment on column TPA_TicketDefinition_t.OverstayingFeeValue is ' 超时补款金额 ';
comment on column TPA_TicketDefinition_t.OverstayingMode is ' 超时补款方式 ';
comment on column TPA_TicketDefinition_t.NoExitFeeValue is ' 进出站不匹配补款（进站端） ';
comment on column TPA_TicketDefinition_t.SurchargeStationMisMatch is ' 非补款车站出站时再次补款金额（出站端） ';
comment on column TPA_TicketDefinition_t.AGMSoundMinBalance is ' 提示最小余额 ';
comment on column TPA_TicketDefinition_t.SaleInitAmount is ' 售卖时初始金额 ';
comment on column TPA_TicketDefinition_t.SaleInitRideNumber is ' 售卖时初始次数 ';
comment on column TPA_TicketDefinition_t.EveryTimeAmount is ' 单次折算金额 ';
comment on column TPA_TicketDefinition_t.ConcessionType is ' 储值票优惠方式 ';
comment on column TPA_TicketDefinition_t.JoinConcessionID is ' 联程优惠代码(BCD) ';
comment on column TPA_TicketDefinition_t.PileConcessionID is ' 累积优惠代码(BCD) ';
comment on column TPA_TicketDefinition_t.EnableFlag is ' 启用标志位, 所有的设备都要检查此标志位(0: 未启用；1:启用) ';
comment on column TPA_DisplayWindow_t.DisplayPictureX is ' 画面左上角X坐标 ';
comment on column TPA_DisplayWindow_t.DisplayPictureY is ' 画面左上角Y坐标 ';
comment on column TPA_DisplayWindow_t.DisplayPictureWidth is ' 画面显示区域（按钮）宽度 ';
comment on column TPA_DisplayWindow_t.DisplayPictureHeight is ' 画面显示区域（按钮）高度 ';
comment on column TPA_EOD_CalendarParam_t.RunStartofDay is ' 运营日切换时间, 建议是2:00 AM';
comment on column TPA_EOD_CalendarParam_t.RunStartTime is ' 运营起始时间 ';
comment on column TPA_EOD_CalendarParam_t.RunEndTime is ' 运营结束时间 ';
comment on column TPA_EOD_CalendarParam_t.BalaStartTime is ' 系统结算起始时间 ';
comment on column TPA_EOD_CalendarParam_t.BalaEndTime is ' 系统结算结束时间 ';
comment on column TPA_EOD_CalendarParam_t.ClearEndTime is ' 系统清算截至时间 ';
comment on column TPA_EOD_CalendarParam_t.AccEndTime is ' 系统对账时间 ';
comment on column TPA_EOD_CalendarParam_t.UrgrelDelayTime is ' 紧急放行模式后票卡延长使用期 ';
comment on column TPA_EOD_CalendarParam_t.TrainfaultDelayTime is ' 列车故障模式后票卡延长使用期 ';
comment on column TPA_EOD_CalendarParam_t.ModeSenTime is ' 模式后果敏感期 ';
--comment on column TPA_EOD_CalendarParam_t.SpecialDates is ' 特殊日期列表 ';
--comment on column TPA_EOD_CalendarParam_t.TimeIntervals is ' 时间段列表  ';
--comment on column TPA_EOD_CalendarParam_t.FareTierTimeTables is ' 最大滞留时间列表 ';
comment on column TPA_TransferStationList_t.StationID is ' 换乘区域内车站(BCD) ';
comment on column TPA_TransferStationList_t.EnableFlag is ' 启用标志位 ';
--comment on column TPA_EOD_TicketParam_t.ChipDefinitions is ' 芯片列表 ';
--comment on column TPA_EOD_TicketParam_t.TicketDefinitions is ' 车票发售表 ';
--comment on column TPA_EOD_TicketParam_t.TicketTypeMaps is ' 票类型映射表 ';
comment on column TPA_EOD_FareParam_t.BankAddingValuePara_id is ' 银行卡充值数据 ';
--comment on column TPA_EOD_FareParam_t.FareGroups is ' 车票费率组定义列表 ';
--comment on column TPA_EOD_FareParam_t.FareTierMatrixDatas is ' 费率等级定义列表 ';
--comment on column TPA_EOD_FareParam_t.BaseFares is ' 基本费率定义列表 ';
comment on column TPA_ConcessionalLampType_t.ConcessionalLampID is ' 灯光显示编号 ';
comment on column TPA_ConcessionalLampType_t.LampColorTypeID is ' 灯光颜色类型 ';
comment on column TPA_ConcessionalLampType_t.Frequency is ' 灯光闪动频率,每分钟次数 ';
comment on column TPA_ConcessionalLampType_t.DisplayPeriod is ' 灯光显示总时长 ';
comment on column TPA_TopBoard_t.TopBoardID is ' 顶板内容编号ID ';
comment on column TPA_TopBoard_t.CNDisplay is ' 顶板显示内容（中文） ';
comment on column TPA_TopBoard_t.ENDisplay is ' 顶板显示内容（英文） ';
comment on column TPA_EOD_RGParam_t.DeviceID is ' 设备节点编号(BCD) ';
--comment on column TPA_EOD_RGParam_t.PassageModeInfos is ' 通行模式信息列表 ';
comment on column TPA_LineBtn_t.LineID is ' 线路选择按钮ID(BCD) ';
comment on column TPA_LineBtn_t.LineBtnDisplay_id is ' 线路选择按钮坐标信息 ';
comment on column TPA_LineBtn_t.LineBtnEnableFlag is ' 线路选择按钮启用标志 0不启用，1启用 ';
comment on column TPA_LineBtn_t.CNLinePicture_id is ' 线路中文图片 ';
comment on column TPA_LineBtn_t.ENLinePicture_id is ' 线路英文图片 ';
comment on column TPA_LineBtn_t.LineDisplay_id is ' 线路坐标信息 ';
comment on column TPA_ResourceFile_t.PictureFileName is ' 图片文件名 ';
comment on column TPA_ResourceFile_t.PictureFileMD5 is ' 图片文件的MD5码 ';
comment on column TPA_EOD_BOMParam_t.BOMControlDefinition_id is ' BOM控制参数 ';
comment on column TPA_EOD_BOMParam_t.IntervalOfMakeFile_id is ' 文件生成时间间隔 ';
--comment on column TPA_EOD_BOMParam_t.ExpressBtnForBOM is ' 票价选择按钮结构（BOM）';
comment on column TPA_ExpressBtn_t.BtnIndex is ' 购票金额按钮ID ';
comment on column TPA_ExpressBtn_t.BuyBtnValue is ' 购票金额按钮显示金额 ';
comment on column TPA_ExpressBtn_t.FareTier is ' 购票金额按钮对应费率等级(BCD) ';
comment on column TPA_ExpressBtn_t.BuyBtnDisplay_id is ' 购票金额按钮显示坐标 ';
--comment on column TPA_EOD_RGParamList_t.EOD_RGParam is 'RG通行控制参数列表';
comment on column TPA_EOD_TVMParam_t.TVMControlDefinition_id is ' TVM的控制参数 ';
comment on column TPA_EOD_TVMParam_t.IntervalOfMakeFile_id is ' 文件生成时间间隔 ';
comment on column TPA_DeviceLoginParam_t.LoginOvertime is ' 登录超时时间 ';
comment on column TPA_DeviceLoginParam_t.MaxPINEntryRetries is ' 错误登录次数上限 ';
--comment on column TPA_EOD_TVM_GUIParam_t.TvmGui is ' 界面列表 ';
comment on column TPA_EOD_PCAParam_t.PCAControlDefinition_id is ' PCA的控制参数 ';
comment on column TPA_EOD_PCAParam_t.IntervalOfMakeFile_id is ' 文件生成时间间隔 ';
comment on column TPA_Station_t.StationID is ' 车站代码(BCD) ';
comment on column TPA_Station_t.StationCNName is ' 车站中文名称 ';
comment on column TPA_Station_t.StationENName is ' 车站英文全称 ';
comment on column TPA_Station_t.LineID is ' 车站所在线路编号(BCD) ';
comment on column TPA_Station_t.EnableFlag is ' 启用标志位 ';
comment on column TPA_TVMControlDefinition_t.SingleFileMaxDeals is ' 单个文件最大交易数量 ';
comment on column TPA_TVMControlDefinition_t.MaxAmountOfBuyTicket is ' 单次购票最大数量 ';
comment on column TPA_TVMControlDefinition_t.MaxIdleToCancelDeal is ' 在限定的时间内无任何后续操作，该项交易将被取消，已投入的钱币将返还乘客 ';
--comment on column TPA_TVMControlDefinition_t.ValidCoinTypes is ' 允许使用硬币类型（面值） ';
--comment on column TPA_TVMControlDefinition_t.ValidBillTypes is ' 允许使用纸币类型（面值） ';
comment on column TPA_TVMControlDefinition_t.MaxAmountOfCoinChange is ' 找零允许最大硬币个数 ';
comment on column TPA_TVMControlDefinition_t.MaxAmountOfNoteChange is ' 找零允许最大纸币张数 ';
comment on column TPA_TVMControlDefinition_t.MaxMoneyOfChangeMoney is ' 找零允许最大金额 ';
comment on column TPA_TVMControlDefinition_t.AlmostFullLimitOfCallbackCoinB is ' 硬币回收箱将满报警值 ';
comment on column TPA_TVMControlDefinition_t.FullLimitOfCallbackCoinBox is ' 硬币回收箱满报警值 ';
comment on column TPA_TVMControlDefinition_t.AlmostEmptyLimitOfReturnCoinBo is ' 硬币找零箱将空报警值 ';
comment on column TPA_TVMControlDefinition_t.EmptyLimitOfReturnCoinBox is ' 硬币找零箱空报警值 ';
comment on column TPA_TVMControlDefinition_t.AlmostFullLimitOfCallbackBillB is ' 纸币回收箱将满报警值 ';
comment on column TPA_TVMControlDefinition_t.FullLimitOfCallbackBillBox is ' 纸币回收箱满报警值 ';
comment on column TPA_TVMControlDefinition_t.AlmostEmptyLimitOfReturnBillBo is ' 纸币找零箱将空报警值 ';
comment on column TPA_TVMControlDefinition_t.EmptyLimitOfReturnBillBox is ' 纸币找零箱空报警值 ';
comment on column TPA_TVMControlDefinition_t.MinWarnOfTicketBox is ' 票箱最低警戒线容量 ';
comment on column TPA_TVMControlDefinition_t.MaxWarnOfInvalidTicketBox is ' 废票箱最大警戒线容量 ';
comment on column TPA_ScreenSize_t.ScreenWidth is ' 屏幕宽度 ';
comment on column TPA_ScreenSize_t.ScreenHeight is ' 屏幕高度 ';
comment on column TPA_SCUploadFile_t.SingleUDFileMaxDeals is ' SC交易文件包最大记录数量 ';
comment on column TPA_SCUploadFile_t.SingleARFileMaxDeals is ' SC审计文件包最大记录数量 ';
comment on column TPA_SCUploadFile_t.IntervalOfBuildYPTUDFile is ' SC交易文件打包上传时间间隔（一票通） ';
comment on column TPA_SCUploadFile_t.IntervalOfBuildYKTUDFile is ' SC交易文件打包上传时间间隔（一卡通） ';
comment on column TPA_SCUploadFile_t.IntervalOfBuildARFile is ' SC审计文件打包上传时间间隔 ';
comment on column TPA_SCUploadFile_t.IntervalOfBuildStockFile is ' SC出入库单文件上传时间间隔 ';
comment on column TPA_ExpressBtnForBOM_t.BtnIndex is ' 购票金额按钮ID ';
comment on column TPA_ExpressBtnForBOM_t.BuyBtnValue is ' 购票金额按钮显示金额 ';
comment on column TPA_ExpressBtnForBOM_t.FareTier is ' 购票金额按钮对应费率等级(BCD) ';
comment on column TPA_EOD_AGMParam_t.AGMControlDefinition_id is ' AGM控制参数 ';
comment on column TPA_EOD_AGMParam_t.IntervalOfMakeFile_id is ' AGM文件生成时间间隔 ';
--comment on column TPA_EOD_AGMParam_t.ConcessionalLampTypes is ' AGM显示灯列表 ';
--comment on column TPA_EOD_AGMParam_t.SoundDisplays is ' AGM语音提示列表 ';
comment on column TPA_TVMGUI_t.TvmGuiId is ' 界面ID ';
comment on column TPA_TVMGUI_t.ScreenSize_id is ' 屏幕尺寸 ';
comment on column TPA_TVMGUI_t.StartupDisplayPicture_id is ' 启动窗口图片文件 ';
comment on column TPA_TVMGUI_t.StartupDisplayWindow_id is ' 启动窗口图片显示坐标 ';
comment on column TPA_TVMGUI_t.PauseDisplayPicture_id is ' 暂停服务窗口图片文件 ';
comment on column TPA_TVMGUI_t.PauseDisplayWindow_id is ' 暂停服务窗口图片显示坐标 ';
comment on column TPA_TVMGUI_t.CNLineZonePicture_id is ' 路网中文图片文件 ';
comment on column TPA_TVMGUI_t.ENLineZonePicture_id is ' 路网英文图片文件 ';
comment on column TPA_TVMGUI_t.LineZoneDisplayWindow_id is ' 路网图片显示坐标 ';
comment on column TPA_TVMGUI_t.ReducePictureWidth is '线网图片缩小后宽度';
comment on column TPA_TVMGUI_t.ReducePictureHeight is '线网图片缩小后高度';
comment on column TPA_TVMGUI_t.LanguageDisplayWindow_id is ' 中英文按钮显示坐标 ';
comment on column TPA_TVMGUI_t.BackDisplayWindow_id is ' 返回按钮显示坐标 ';
comment on column TPA_TVMGUI_t.AddValueDisplayWindow_id is ' 充值按钮显示坐标 ';
--comment on column TPA_TVMGUI_t.AddValueBtns is ' 充值选择按钮列表 ';
comment on column TPA_TVMGUI_t.CheckCardDisplayWindow_id is ' 验卡按钮显示坐标 ';
comment on column TPA_TVMGUI_t.NowtimeDisplayWindow_id is ' 当前日期时间显示坐标 ';
comment on column TPA_TVMGUI_t.NowStationDisplayWindow_id is ' 当前车站显示坐标 ';
comment on column TPA_TVMGUI_t.RunningStatusDisplayWindow_id is ' 运行状态显示坐标 ';
--comment on column TPA_TVMGUI_t.ADItems is ' 广告列表（预留） ';
comment on column TPA_TVMGUI_t.ADPlayType is ' 广告播放方式 0从头开始，1继续播放（预留） ';
comment on column TPA_TVMGUI_t.MaxIdleToPlayAD is ' 进入广告模式的最大空闲时间（预留） ';
--comment on column TPA_TVMGUI_t.TopBoards is ' 顶板列表 ';
--comment on column TPA_TVMGUI_t.FareSelBtns is ' 票价选择按钮列表 ';
--comment on column TPA_TVMGUI_t.NumbersSelBtns is ' 张数选择按钮列表 ';
--comment on column TPA_TVMGUI_t.StationBtnInLineZones is ' 路网区域中车站按钮列表 ';
--comment on column TPA_TVMGUI_t.LineBtns is ' 线路选择按钮列表 ';
--comment on column TPA_TVMGUI_t.StationBtnInLines is ' 线路中车站选择按钮列表 ';
comment on column TPA_TVMGUI_t.CNPayInterfacePicture_id is ' 支付界面中文图片文件 ';
comment on column TPA_TVMGUI_t.ENPayInterfacePicture_id is ' 支付界面英文图片文件 ';
comment on column TPA_TVMGUI_t.PayInterfaceDisplayWindow_id is ' 支付界面显示坐标 ';
--comment on column TPA_TVMGUI_t.PayInterfacePositions is ' 支付界面相关位置显示坐标 ';
comment on column TPA_PCAControlDefinition_t.SingleFileMaxDeals is ' 单个文件最大交易数量 ';
comment on column TPA_PCAControlDefinition_t.MaxIdleToCancelDeal is ' 等待操作最长时间，超出时间则取消操作，并返回初始界面 ';
comment on column TPA_PassageModeInfo_t.PassageMode is ' 通行模式 ';
comment on column TPA_PassageModeInfo_t.BeginTime is ' 开始时间 ';
comment on column TPA_PassageModeInfo_t.EndTime is ' 结束时间 ';
comment on column TPA_SpecialDate_t.SpecialDate is ' 特殊日期 ';
comment on column TPA_SpecialDate_t.DateTypeID is ' 日期类型 ';
comment on column TPA_BankAddingValuePara_t.BankCardPaymentMinAmount is ' 银行卡充值的最小金额 ';
comment on column TPA_BankAddingValuePara_t.BankCardPaymentMaxAmount is ' 银行卡充值的最大金额 ';
--comment on column TPA_EOD_ConcessionParam_t.JoinConcessionDefinitions is ' 联程优惠列表 ';
--comment on column TPA_EOD_ConcessionParam_t.PileConcessionDefinitions is ' 累积优惠列表 ';
comment on column TPA_PileConcessionDefinition_t.PileConcessionID is ' 累积优惠代码(BCD) ';
comment on column TPA_PileConcessionDefinition_t.PileConcessionType is ' 累积优惠方式(0：累积次数优惠，1：累积金额优惠) ';
comment on column TPA_PileConcessionDefinition_t.PileConcessionTime is ' 累积乘坐起始优惠次数 ';
comment on column TPA_PileConcessionDefinition_t.PileConcessionAmount is ' 累积乘坐起始优惠金额 ';
comment on column TPA_PileConcessionDefinition_t.JoinConcessionPercentage is ' 累积乘坐优惠比例 ';
comment on column TPA_PileConcessionDefinition_t.ConcessionResetType is ' 优惠重置类型(0－按月重置 1－按季重置 2－按年重置 3－不重置) ';
comment on column TPA_EOD_RGParam_t.DeviceID is ' 设备节点编号(BCD) ';
--comment on column TPA_EOD_RGParam_t.PassageModeInfos is ' 通行模式信息列表 ';
comment on column TPA_PassageModeInfo_t.PassageMode is ' 通行模式 ';
comment on column TPA_PassageModeInfo_t.BeginTime is ' 开始时间 ';
comment on column TPA_PassageModeInfo_t.EndTime is ' 结束时间 ';