stages:
  - build
  - deploy

build:
  stage: build
  image: maven:3.6-jdk-8
  script:
    - mvn clean
    - mvn compile
    - mvn package
    - pwd
  artifacts:
    paths:
      - ./afc-monitor-api/target/afc-monitor-api-0.0.1-SNAPSHOT.jar
  tags:
    - build
  only:
    refs:
      - master
      - XSY

deploy:
  stage: deploy
  script:
    - ls
    - pwd
    - scp ./afc-monitor-api/target/afc-monitor-api-0.0.1-SNAPSHOT.jar afc@192.168.140.100:/home/afc/xz-monitor/afc-monitor-dev/
    - ssh afc@192.168.140.100 "cd /home/afc/xz-monitor/afc-monitor-dev/;kill \`cat application.pid\`;nohup java -jar afc-monitor-api-0.0.1-SNAPSHOT.jar >/dev/null 2>&1 &"
  tags:
    - deploy
  only:
    refs:
      - master
      - XSY
