stages:
  - build
  - deploy

build:
  stage: build
  image: maven:3.6-jdk-8
  script:
    - mvn clean
    - mvn compile
    - mvn package
    - pwd
  artifacts:
    paths:
      - ./afc-monitor-api/target/*.jar
  tags:
    - build
  only:
    refs:
      - master

deploy:
  stage: deploy
  script:
    - ls
    - pwd
    - scp ./afc-monitor-api/target/*.jar afc@192.168.140.100:/home/afc/xz-monitor/afc-monitor-dev/
    - ssh afc@192.168.140.100 "cd /home/afc/xz-monitor/afc-monitor-dev/;kill \`cat application.pid\`;sh start.sh"
  tags:
    - deploy
  only:
    refs:
      - master
