package com.insigma.afc.monitor.model.xdr.typedef;

/*
 *;
 */
public interface FileHeaderTag_t {
	// 一票通交易文件 ;
	public final static int FILE_YPT_TRANSACTION = 0x01;
	// 一卡通交易文件 ;
	public final static int FILE_YKT_TRANSACTION = 0x02;
	// 手机卡交易文件 ;
	public final static int FILE_MOBILE_TRANSACTION = 0x03;
	// 银行卡交易文件 ;
	public final static int FILE_BANK_TRANSACTION = 0x04;
	// AGM审计文件 ;
	public final static int FILE_AGM_AUDIT_REGISTER = 0x05;
	// BOM审计文件 ;
	public final static int FILE_BOM_AUDIT_REGISTER = 0x06;
	// TVM审计文件 ;
	public final static int FILE_TVM_AUDIT_REGISTER = 0x07;
	// ISM审计文件 ;
	public final static int FILE_ISM_AUDIT_REGISTER = 0x08;
	// PCA审计文件 ;
	public final static int FILE_PCA_AUDIT_REGISTER = 0x09;
	// ES交易文件 ;
	public final static int FILE_ES_TRANSACTION = 0x0A;
	// ES编码报告文件 ;
	public final static int FILE_ES_ENCODING = 0x0B;
	//二维码交易文件;
	public final static int FILE_QRCODE_TRANSACTION = 0x0C;
	// EOD参数控制文件 ;
	public final static int FILE_EOD_CONTROL = 0x20;
	// EOD: 系统参数文件 ;
	public final static int FILE_EOD_SYSTEM = 0x21;
	// EOD: 网络拓扑参数文件 ;
	public final static int FILE_EOD_SYSNetwork = 0x22;
	// EOD: 日历时间参数文件 ;
	public final static int FILE_EOD_SYSCalendar = 0x23;
	// EOD: 费率表参数文件 ;
	public final static int FILE_EOD_SYSFare = 0x24;
	// EOD: 车票参数文件 ;
	public final static int FILE_EOD_SYSTicket = 0x25;
	// EOD: 优惠方案参数文件 ;
	public final static int FILE_EOD_Concession = 0x26;
	// EOD: AGM设备参数文件 ;
	public final static int FILE_EOD_AGM = 0x27;
	// EOD: RG通行控制参数文件 ;
	public final static int FILE_EOD_RG = 0x28;
	// EOD: BOM设备参数文件 ;
	public final static int FILE_EOD_BOM = 0x29;
	// EOD: TVM设备参数文件 ;
	public final static int FILE_EOD_TVM = 0x2A;
	// EOD: TVM界面参数文件 ;
	public final static int FILE_EOD_TVM_GUI = 0x2B;
	// EOD: ISM参数文件 ;
	public final static int FILE_EOD_ISM = 0x2C;
	// EOD: PCA参数文件 ;
	public final static int FILE_EOD_PCA = 0x2D;
	//TVM软件程序文件;
	public final static int FILE_TVM_Soft = 0x2E;
	//BOM软件程序文件;
	public final static int FILE_BOM_Soft = 0x2F;
	//AGM软件程序文件;
	public final static int FILE_AGM_Soft = 0x30;
	//ISM软件程序文件;
	public final static int FILE_ISM_Soft = 0x31;
	//TP软件程序文件;
	public final static int FILE_TP_Soft = 0x32;
	//PCA软件程序文件;
	public final static int FILE_PCA_Soft = 0x33;
	// AFC运营主控文件 ;
	public final static int FILE_AFC_MAIN_CONTROL = 0x40;
	// 一票通全量明细黑名单文件 ;
	public final static int FILE_BLK_ACC_FULL_LIST = 0x41;
	// 一票通增量明细黑名单文件 ;
	public final static int FILE_BLK_ACC_INCR_LIST = 0x42;
	// 一票通全量号段黑名单文件 ;
	public final static int FILE_BLK_ACC_FULL_SECT = 0x43;
	// 一卡通全量明细黑名单文件（预留） ;
	public final static int FILE_BLK_YKT_FULL_LIST = 0x44;
	// 员工卡全量明细黑名单文件 ;
	public final static int FILE_BLK_STAFF_FULL_LIST = 0x45;
	// 单程票回收条件文件 ;
	public final static int FILE_SJT_RECYCLE = 0x46;
	// 模式履历文件 ;
	public final static int FILE_WAIVERDATE = 0x47;
	// 票卡库存目录文件 ;
	public final static int FILE_TICKET_CATALOG = 0x48;
	// 车站设备节点配置信息文件 ;
	public final static int FILE_STATION_EQUNODE_CONFIG = 0x49;
	// 操作员基本信息文件 ;
	public final static int FILE_OPERINFO = 0x50;
	// 操作员权限文件 ;
	public final static int FILE_OPERRIGHT = 0x51;
	//二维码公钥证书文件;
	public final static int FILE_QRCODEPKI = 0x52;
	// 出入库清单文件 ;
	public final static int FILE_STOCK_INOUT_BILL = 0x60;
	// 日终库存快照文件 ;
	public final static int FILE_ENDOFDAY_STOCK_SANPSHOT = 0x61;
	// 日终库存差异文件 ;
	public final static int FILE_ENDOFDAY_STOCK_DIFF = 0x62;
	// 交易对账文件 ;
	public final static int FILE_TRANS_ACCOUNT = 0x63;
	// 可疑交易处理文件 ;
	public final static int FILE_DOUBTFULDEAL_RESULT = 0x64;
	// 与市民卡对账文件 ;
	public final static int FILE_COMPARISON_WITH_YKT = 0x65;
	// 与移动对账文件 ;
	public final static int FILE_COMPARISON_WITH_MOBILE = 0x66;
	// 与银联对账文件 ;
	public final static int FILE_COMPARISON_WITH_BANK = 0x67;
}
