package com.insigma.afc.monitor.constant.xdr.typedef;

/*
 *;
 */
public interface MessageType_t {
	//ping命令;
	public final static int MT_Mack = 0x1000;
	//通讯链接申请;
	public final static int MT_InitForTx = 0x1001;
	//数据同步下载指令;
	public final static int MT_DataSynch = 0x1002;
	//查询运行配置文件版本;
	public final static int MT_QueryRunfileVersion = 0x1003;
	//查询参数版本;
	public final static int MT_QueryEODVersion = 0x1004;
	//下发车站模式更新指令;
	public final static int MT_CommandMode = 0x1005;
	//上传车站模式更新信息;
	public final static int MT_InfoMode = 0x1006;
	//车站模式广播指令;
	public final static int MT_BroadCastMode = 0x1007;
	//查询车站模式信息;
	public final static int MT_QueryMode = 0x1008;
	//上传综合客流信息;
	public final static int MT_InfoFlowData = 0x1009;
	//上传设备信息状态;
	public final static int MT_InfoDeviceStatus = 0x100a;
	//查询设备状态指令;
	public final static int MT_QueryDeviceStatus = 0x100b;
	//预留1;
	public final static int MT_Reserved1 = 0x100c;
	//预留2;
	public final static int MT_Reserved2 = 0x100d;
	//时钟强制同步指令;
	public final static int MT_CommandTimeSynch = 0x100e;
	//设备控制指令;
	public final static int MT_CommandEQM = 0x100f;
	//上传设备事件;
	public final static int MT_InfoDeviceEvent = 0x1010;
	//用户权限认证指令;
	public final static int MT_UserAuthenticate = 0x1021;
	//轨道交通储值票联机认证指令;
	public final static int MT_YPTCardAuthenticate = 0x1022;
	//用户口令修改指令;
	public final static int MT_UserPinChange = 0x1023;
	//库存调拨申请报文;
	public final static int MT_StockApply = 0x1601;
	//库存调拨命令报文;
	public final static int MT_StockCommand = 0x1602;
	//要求下级上报库存信息报文;
	public final static int MT_StockReportInformation = 0x1603;
	//一票通交易文件;
	public final static int MT_YptTransaction = 0x2001;
	//一卡通交易文件;
	public final static int MT_YktTracsaction = 0x2002;
	//设备收益文件;
	public final static int MT_SleFinance = 0x2003;
	//设备审计文件;
	public final static int MT_SleAuditRegister = 0x2004;
	//地铁CPU卡交易文件;
	public final static int MT_SVTCPUCardTransaction = 0x2005;
	//交通部CPU卡交易文件;
	public final static int MT_JTBCardTransaction = 0x2006;
	//设备事件文件;
	public final static int MT_SLEEVENTMSG = 0x3001;
	//参数控制文件;
	public final static int MT_EodMasterControl = 0x4001;
	//运营配置控制文件;
	public final static int MT_RunMasterControl = 0x4002;
	//外部参数主控文件;
	public final static int MT_OtherMasterControl = 0x4003;
	//一卡通黑名单文件;
	public final static int MT_YktBlacklist = 0x4011;
	//一票通黑名单全量文件;
	public final static int MT_YptAllBlackList = 0x4012;
	//一票通号段黑名单;
	public final static int MT_YptRangeBlackList = 0x4014;
	//模式履历;
	public final static int MT_ModeHistoryList = 0x4021;
	//系统控制参数文件;
	public final static int MT_EodSystemControl = 0x4031;
	//路网信息参数文件;
	public final static int MT_EodTopo = 0x4032;
	//车票参数参数文件;
	public final static int MT_EodFareMediaType = 0x4033;
	//优惠方案参数文件;
	public final static int MT_EodDiscount = 0x4034;
	//日历时间段参数文件;
	public final static int MT_EodCalendar = 0x4035;
	//费率参数文件;
	public final static int MT_EodFare = 0x4036;
	//TVM界面参数文件;
	public final static int MT_EodTvmUi = 0x4037;
	//列车首末班车时刻文件;
	public final static int MT_EodTrainSchedule = 0x4038;
	//车票映射关系文件;
	public final static int MT_EodDataTicketMType = 0x4039;
	//权限参数文件;
	public final static int MT_EodPriviledge = 0x4041;
	//车站设备节点配置文件;
	public final static int MT_EodStationLayout = 0x4042;
	//TVM运营参数文件;
	public final static int MT_EodTvmRunConfig = 0x4043;
	//AGM运营参数文件;
	public final static int MT_EodAgmRunConfig = 0x4044;
	//BOM运营参数文件;
	public final static int MT_EodBomRunConfig = 0x4045;
	//交通部CPU卡白名单
	public final static int MT_JTBAllWhiteList = 0x4054;
	//TP;
	public final static int MT_TP = 0x4058;
	//设备软件;
	public final static int MT_SleSoftware = 0x4091;
	//库存快照文件;
	public final static int MT_TicketStockSnapshot = 0x5001;
	//文件对账审计;
	public final static int MT_FtpAudit = 0x6001;
	//交易对账文件;
	public final static int MT_AccSettleTxResult = 0x6002;
	//可疑交易调整文件;
	public final static int MT_AccSettleTxAdjust = 0x6003;
	//清分结果文件;
	public final static int MT_AccSettleClear = 0x6004;
	//设备签到请求;
	public final static int MT_ESLogin = 0x1A01;
	//设备签退;
	public final static int MT_ESLogout = 0x1A02;
	//操作员签到请求;
	public final static int MT_OperatorLogin = 0x1A03;
	//操作员签退;
	public final static int MT_OperatorLogout = 0x1A04;
	//设备工作任务请求;
	public final static int MT_Task = 0x1A05;
	//工作任务报告;
	public final static int MT_TaskReport = 0x1A06;
	//设备状态报告;
	public final static int MT_StatusReport = 0x1A07;
	//自定义默认
	public final static int DEFAULT = 0xFF0F;
}
