#server配置
server:
  port: 8080
  tomcat:
    #tomcat工作目录
    basedir: ./
#spring配置
spring:
  datasource:
    url: jdbc:oracle:thin:@192.168.144.182:1521:afclc
    username: acc_wenzhou_v2
    password: afcapp
    driver-class-name: oracle.jdbc.driver.OracleDriver
    dbcp2:
      #获取连接时不检查可用性
      test-on-borrow: false
      #检查可用性sql
      validation-query: select 'x'
      #执行可用性sql超时时间
      validation-query-timeout: 60000
      max-total: 20
      min-idle: 1
      max-idle: 5
      #空闲时检查可用性
      test-while-idle: true
      #空闲时每隔10秒检查可用性
      time-between-eviction-runs-millis: 10000
      #每次检查5个连接
      num-tests-per-eviction-run: 5
