package com.insigma.acc.wz.xdr.typedef;

/*
 *;
 */
public interface ComType_t {
	// 通讯链接申请 ;
	public final static int COM_COMM_CONNECT_APPLY = 0x1001;
	// 应用层PING ;
	public final static int COM_PING = 0x1101;
	// 文本消息 ;
	public final static int COM_TEXT = 0x1102;
	// 设备控制命令 ;
	public final static int COM_SLE_CONTROL_CMD = 0x1103;
	// 强制时钟同步命令 ;
	public final static int COM_TIME_SYNC = 0x1104;
	// 设备事件上传 ;
	public final static int COM_EVENT_UPLOAD = 0x1201;
	// 查询下级参数版本 ;
	public final static int COM_QUERY_EOD_VERSION = 0x1202;
	// 查询运行配置文件版本 ;
	public final static int COM_QUERY_FILE_VERSION = 0x1203;
	// 查询设备交易流水号 ;
	public final static int COM_QUERY_TRANS_SN = 0x1205;
	// 设备参数版本变化上传 ;
	public final static int COM_UPLOAD_EOD_VERSION = 0x1206;
	// 设备运行配置文件版本上传 ;
	public final static int COM_UPLOAD_FILE_VERSION = 0x1207;
	// 设备SAM信息上传 ;
	public final static int COM_UPLOAD_SAM = 0x1208;
	// 设备最新流水号上传 ;
	public final static int COM_UPLOAD_SN = 0x1210;
	// 设置运营结束时间 ;
	public final static int COM_EndTime_SET = 0x1211;
	// 操作员登录、暂停、恢复和退出等操作 ;
	public final static int COM_OPERATOR_WORK = 0x1301;
	// 票箱操作数据上传 ;
	public final static int COM_TICKETBOX_OPERATE = 0x1303;
	// 纸币钱箱操作数据上传 ;
	public final static int COM_BANKNOTEBOX_OPERATE = 0x1304;
	// 硬币钱箱操作数据上传 ;
	public final static int COM_COINBOX_OPERATE = 0x1305;
	// TVM硬币钱箱清空数据上传 ;
	public final static int COM_COINBOX_CLEAR = 0x1306;
	// 纸币钱箱清空数据上传 ;
	public final static int COM_NOTEBOX_CLEAR = 0x1307;
	// 查询设备钱箱数据 ;
	public final static int COM_CASHBOX_QUERY = 0x1308;
	// 设备钱箱数据上传 ;
	public final static int COM_CASHBOX_UPLOAD = 0x1309;
	//查询设备票箱数据;
	public final static int COM_TICKETBOX_QUERY = 0x1310;
	//设备票箱数据上传;
	public final static int COM_TICKETBOX_UPLOAD = 0x1311;
	// FTP申请 ;
	public final static int COM_FTP_APPLY = 0x1401;
	// 文件更新通知 ;
	public final static int COM_FILE_UPDATE_NOTIFY = 0x1402;
	// 当前文件上传通知 ;
	public final static int COM_CURFILE_UPLOAD_NOTIFY = 0x1403;
	// 指定文件上传通知 ;
	public final static int COM_SPECFILE_UPLOAD_NOTIFY = 0x1404;
	// 启动/解除紧急运营模式 ;
	public final static int COM_SEND_EMERGENCY_MODE = 0x1501;
	// 发送其他运营模式命令 ;
	public final static int COM_SEND_OTHER_MODE = 0x1502;
	// 模式状态上传 ;
	public final static int COM_MODE_STATUS_UPLOAD = 0x1503;
	// 模式变更广播 ;
	public final static int COM_MODE_CHANGE_BROADCAST = 0x1504;
	// 车站模式查询 ;
	public final static int COM_MODE_QUERY = 0x1505;
	// 票卡调拨申请 ;
	public final static int COM_TICKET_ALLOC_APPLY = 0x1601;
	// 票卡调拨命令 ;
	public final static int COM_TICKET_ALLOC_ORDER = 0x1602;
	//通知下级上传票卡库存信息 ;
	public final static int COM_UPLOAD_TICKET_STOCK_NOTIFY = 0x1603;
	//上传票卡库存信息 ;
	public final static int COM_UPLOAD_TICKET_STOCK = 0x1604;
	//上传票款收益信息 ;
	public final static int COM_UPLOAD_TICKET_INCOME = 0x1605;
	//客值交接班信息上报 ;
	public final static int COM_UPLOAD_CHANGESHIFTS_RECORD = 0x1606;
	//短款补款信息通知 ;
	public final static int COM_TICKET_FILLINGMONEY_NOTICE = 0x1607;
	//短款补款信息上报 ;
	public final static int COM_UPLOAD_TICKET_FILLINGMONEY = 0x1608;
	//设备现金登记日报上报 ;
	public final static int COM_UPLOAD_CASH_FORM = 0x1609;
	//BOM售票员结算单上报 ;
	public final static int COM_UPLOAD_SELLER_STATEMENTS = 0x1610;
	//车站营收日报上报 ;
	public final static int COM_UPLOAD_STATION_REVENUEDAILY = 0x1611;
	//特殊情况车票即时退款信息上报 ;
	public final static int COM_UPLOAD_STATION_IMMEDIATE_REFUND = 0x1612;
	//车站票卡售存信息上报 ;
	public final static int COM_UPLOAD_TICKET_INFO = 0x1613;
	//车站票卡盘点信息上报 ;
	public final static int COM_UPLOAD_TICKET_INVENTORY = 0x1614;
	//车站备用金清点信息上报 ;
	public final static int COM_UPLOAD_RESERVEFUNDS_INFO = 0x1615;
	//特殊情况票款信息上报 ;
	public final static int COM_UPLOAD_SPECFUNDS_INFO = 0x1616;
	//纸票发售信息上报 ;
	public final static int COM_UPLOAD_PAPERTICKET_SALEINFO = 0x1617;
	//设备补币、清点信息上报 ;
	public final static int COM_UPLOAD_SLECASH_OPERINFO = 0x1618;
	//客服结算单信息上报 ;
	public final static int COM_UPLOAD_CUSTOMERSERVICE_STATEMENTS = 0x1619;
	// BOM在线充值认证 ;
	public final static int COM_BOM_ADDVALUE_AUTH = 0x1701;
	// BOM在线充值确认 ;
	public final static int COM_BOM_ADDVALUE_AFFIRM = 0x1702;
	// 个性化卡申请 ;
	public final static int COM_PERSONAL_CARD_APPLY = 0x1703;
	// 非即时退款申请 ;
	public final static int COM_NONIMMEDIATE_REFUND_APPLY = 0x1704;
	// 非即时退款查询 ;
	public final static int COM_NONIMMEDIATE_REFUND_QUERY = 0x1705;
	// 票卡挂失 ;
	public final static int COM_TICKET_LOST = 0x1706;
	// 票卡解挂 ;
	public final static int COM_TICKET_DISLOST = 0x1707;
	// 非即时退款信息下发 ;
	public final static int COM_NONIMMEDIATE_REFUND_SEND = 0x1708;
	// 票卡帐户查询 ;
	public final static int COM_CARD_ACCOUNT_QUERY = 0x1709;
	// 票卡账户信息下发 ;
	public final static int COM_CARD_ACCOUNT_SEND = 0x1710;
	//福利票发售信息上传 ;
	public final static int COM_UPLOAD_WEALTICKETINFO = 0x1711;
	//车站乘客事务处理信息上报 ;
	public final static int COM_UPLOAD_PASSENGERAFFAIRINFO = 0x1712;
	//车站非即时退款申请 ;
	public final static int COM_STATION_NONIMMEDIATE_REFUND_APPLY = 0x1713;
	// 车站报修申请 ;
	public final static int COM_STATION_MAINTAIN_APPLY = 0x1801;
	// 车站维修结果确认 ;
	public final static int COM_STATION_MAINTAIN_AFFIRM = 0x1802;
	// 操作员密码更新 ;
	public final static int COM_UPDATE_PASSWORD = 0x1901;
	// 设备签到请求 ;
	public final static int COM_ES_LOGIN = 0x1A01;
	// 设备签退 ;
	public final static int COM_ES_LOGOUT = 0x1A02;
	// 操作员签到请求 ;
	public final static int COM_OPERATOR_LOGIN = 0x1A03;
	// 操作员签退 ;
	public final static int COM_OPERATOR_LOGOUT = 0x1A04;
	// 设备工作任务请求 ;
	public final static int COM_WORK_TASK = 0x1A05;
	// 工作任务报告 ;
	public final static int COM_TASK_REPORT = 0x1A06;
	// 设备状态报告 ;
	public final static int COM_STATUS_REPORT = 0x1A07;
	//;
	public final static int DEFAULT = 0xFF0F;
}
