package com.insigma.acc.wz.xdr.typedef;

/*
 *;
 */
public interface TransactionType_t {
	// 单程票发售 ;
	public final static int TX_SJTSale = 0x01;
	// 非记名储值票发售 ;
	public final static int TX_NonNamedCPUSale = 0x02;
	// 记名储值票发售 ;
	public final static int TX_NamedCPUSale = 0x03;
	// 储值票充值 ;
	public final static int TX_CPUCardAddValue = 0x04;
	// 单程票即时退票 ;
	public final static int TX_SJTRefund = 0x05;
	// 储值票即时退票 ;
	public final static int TX_CPUCardImmediateRefund = 0x06;
	// 储值票非即时退票 ;
	public final static int TX_CPUCardNonImmediateRefund = 0x07;
	// 储值票延期 ;
	public final static int TX_TicketValidityPeriod = 0x08;
	// 储值票锁卡 ;
	public final static int TX_CPUCardBlock = 0x09;
	// 储值票解锁 ;
	public final static int TX_CPUCardUnblock = 0x0A;
	// 一票通更新 ;
	public final static int TX_TicketSurcharge = 0x0B;
	// 一票通进站 ;
	public final static int TX_TicketEntry = 0x0C;
	// 一票通出站;
	public final static int TX_TicketExit = 0x0D;
	// 储值票扣款（预留） ;
	public final static int TX_CPUCardDeduction = 0x0E;
	// 一卡通售卖（预留） ;
	public final static int TX_YKTSale = 0x20;
	// 一卡通充值（预留） ;
	public final static int TX_YKTCardAddValue = 0x21;
	// 一卡通锁卡（预留） ;
	public final static int TX_YKTCardBlock = 0x22;
	// 一卡通解锁（预留） ;
	public final static int TX_YKTCardUnblock = 0x23;
	// 一卡通更新 ;
	public final static int TX_YKTCardSurcharge = 0x24;
	// 一卡通进站 ;
	public final static int TX_YKTCardEntry = 0x25;
	// 一卡通出站;
	public final static int TX_YKTCardExit = 0x26;
	// 一卡通扣款（预留） ;
	public final static int TX_YKTCardDeduction = 0x27;
	// 手机卡更新 ;
	public final static int TX_MobileSurcharge = 0x40;
	// 手机卡进站 ;
	public final static int TX_MobileEntry = 0x41;
	// 手机卡出站;
	public final static int TX_MobileExit = 0x42;
	// 手机卡扣款 （预留） ;
	public final static int TX_MobileDeduction = 0x43;
	//银行卡扣款;
	public final static int TX_BankCardDeduction = 0x60;
	//银行卡更新;
	public final static int TX_BankCardSurcharge = 0x61;
	//银行卡进站;
	public final static int TX_BankCardEntry = 0x62;
	//银行卡出站;
	public final static int TX_BankCardExit = 0x63;
	// 单程票初始化 ;
	public final static int TX_SJTInit = 0x80;
	// 储值票初始化 ;
	public final static int TX_CPUCardInit = 0x81;
	// 票卡注销 ;
	public final static int TX_TicketCancel = 0x82;
	// 储值票个性化 ;
	public final static int TX_CPUCardPersonal = 0x83;
	// 预付值单程票抵销 ;
	public final static int TX_PrePaySJTOffset = 0x84;
	//二维码更新;
	public final static int TX_QRCodeSurcharge = 0x90;
	//二维码进站;
	public final static int TX_QRCodeEntry = 0x91;
	//二维码出站;
	public final static int TX_QRCodeExit = 0x92;
}
