openapi: 3.0.2
servers:
  - url: 'http://localhost:8080/'
info:
  description: AFC监控系统前后台接口-路网监控-节点命令
  version: 1.0.0
  title: AFC监控系统前后台接口-路网监控-节点命令
tags:
  - name: 路网监控-命令
paths:
  /monitor/command/changeMode:
    post:
      tags:
        - 路网监控
      summary: 修改运营模式。
      description: 修改运营模式
      operationId: monitor-changeMode
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                nodeIds:
                  type: array
                  description: 目标节点的Id
                  items:
                    type: number
                command:
                  description: 运营模式
                  type: number
      responses:
        '200':
          description: 返回命令执行结果。
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CommandResponse'
  /monitor/command/queryMode:
    post:
      tags:
        - 路网监控
      summary: 查询运营模式。
      description: 查询运营模式
      operationId: monitor-changeMode
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                nodeIds:
                  type: array
                  description: 目标节点的Id
                  items:
                    type: number
      responses:
        '200':
          description: 返回命令执行结果。
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CommandResponse'
  /monitor/command/timeSync:
    post:
      tags:
        - 路网监控
      summary: 时钟同步。
      description: 时钟同步
      operationId: monitor-time-sync
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                nodeIds:
                  type: array
                  description: 目标节点的Id
                  items:
                    type: number
      responses:
        '200':
          description: 返回命令执行结果。
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CommandResponse'
  /monitor/command/nodeControl:
    post:
      tags:
        - 路网监控
      summary: 发送控制命令。
      description: 发送控制命令
      operationId: monitor-nodeControl
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                nodeIds:
                  type: array
                  description: 目标节点的Id
                  items:
                    type: number
                command:
                  description: 运营模式
                  type: number
      responses:
        '200':
          description: 返回命令执行结果。
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CommandResponse'
  /monitor/command/queryBox:
    post:
      tags:
        - 路网监控
      summary: 查询票箱或者钱箱信息。
      description: 查询票箱或者钱箱信息
      operationId: monitor-query-box
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                nodeId:
                  type: number
                  description: 目标节点的Id
      responses:
        '200':
          description: 返回命令执行结果。
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CommandBoxQueryResult'
  /monitor/command/refresh:
    post:
      tags:
        - 路网监控
      summary: 刷新数据。刷新后，界面要重新构建。
      description: 刷新数据
      operationId: monitor-refresh
      responses:
        '200':
          description: 成功。
  /monitor/config/get:
    get:
      tags:
        - 路网监控
      summary: 获取配置数据。
      description: 获取配置数据。
      operationId: monitor-config-get
      responses:
        '200':
          description: 返回命令执行结果。
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NetMonitorConfig'
  /monitor/config/save:
    post:
      tags:
        - 路网监控
      summary: 更新配置数据。
      description: 更新配置数据
      operationId: monitor-config-post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NetMonitorConfig'
      responses:
        '200':
          description: ok
components:
  schemas:
    DeviceDetail:
      description: 描述设备及模块的的详细信息
      type: object
      properties:
        device:
          description: 设备名称和id
          type: string
        imgUrl:
          description: 底图索引
          type: number
        station:
          description: 车站名称
          type: string
        modules:
          description: 设备模块信息
          type: array
          items:
            type: object
            properties:
              moduleName:
                description: 部件简写
                type: string
              status:
                description: 模块状态
                type: number
              statusText:
                description: 模块状态名称(正常，警告，报警)
                type: string
              remark:
                description: 部件名称
                type: string
              location:
                description: 模块在设备底图上的文字的位置。
                type: object
                properties:
                  x:
                    type: number
                  'y':
                    type: number
                  angle:
                    type: number
    CommandResponse:
      description: 向下级节点发送命令的返回值，参考CommandResult类
      type: array
      items:
        type: object
        properties:
          id:
            description: 目标节点Id
            type: string
          cmdName:
            description: 命令名称
            type: string
          cmdResult:
            description: 命令结果
            type: string
          occurTime:
            description: 发送时间
            type: string
    CommandBoxQueryResult:
      description: 设备钱箱、票箱查询结果
      type: object
      properties:
        ticketBoxList:
          type: array
          description: 票箱数据
          items:
            type: object
            properties:
              deviceTicketBoxInfo:
                description: 票箱名称
                type: string
              deviceTicketBoxValue:
                description: 票卡数量
                type: string
        cashBoxList:
          type: array
          description: 钱箱数据
          items:
            type: object
            properties:
              deviceCashBoxInfo:
                description: 钱箱名称
                type: string
              deviceCashBoxValue:
                description: 钱箱金额
                type: string
    NetMonitorConfig:
      description: 路网监控下的监控配置
      type: object
      properties:
        warning:
          description: 警告阈值（个）
          type: number
        alarm:
          description: 报警阈值（个）
          type: number
        interval:
          description: 刷新阈值（秒）
          type: number
