package com.insigma.afc.odmonitor.entity;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TmoSectionOdFlowStatsId generated by MyEclipse Persistence Tools
 */
@Embeddable
public class TmoSectionOdFlowStatsId implements java.io.Serializable {

	private static final long serialVersionUID = -1588250417219484748L;

	private Long sectionId;

	private Date gatheringDate;

	private Long timeIntervalId;

	// Constructors

	/** default constructor */
	public TmoSectionOdFlowStatsId() {
	}

	/** full constructor */
	public TmoSectionOdFlowStatsId(Long sectionId, Date gatheringDate, Long timeIntervalId) {
		this.sectionId = sectionId;
		this.gatheringDate = gatheringDate;
		this.timeIntervalId = timeIntervalId;
	}

	// Property accessors
	@Column(name = "SECTION_ID", length = 19, nullable = false)
	public Long getSectionId() {
		return this.sectionId;
	}

	public void setSectionId(Long sectionId) {
		this.sectionId = sectionId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "GATHERING_DATE", length = 11, nullable = false)
	public Date getGatheringDate() {
		return this.gatheringDate;
	}

	public void setGatheringDate(Date gatheringDate) {
		this.gatheringDate = gatheringDate;
	}

	@Column(name = "TIME_INTERVAL_ID", length = 11, nullable = false)
	public Long getTimeIntervalId() {
		return this.timeIntervalId;
	}

	public void setTimeIntervalId(Long timeIntervalId) {
		this.timeIntervalId = timeIntervalId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TmoSectionOdFlowStatsId))
			return false;
		TmoSectionOdFlowStatsId castOther = (TmoSectionOdFlowStatsId) other;

		return ((this.getSectionId() == castOther.getSectionId()) || (this.getSectionId() != null
				&& castOther.getSectionId() != null && this.getSectionId().equals(castOther.getSectionId())))
				&& ((this.getGatheringDate() == castOther.getGatheringDate())
						|| (this.getGatheringDate() != null && castOther.getGatheringDate() != null
								&& this.getGatheringDate().equals(castOther.getGatheringDate())))
				&& ((this.getTimeIntervalId() == castOther.getTimeIntervalId())
						|| (this.getTimeIntervalId() != null && castOther.getTimeIntervalId() != null
								&& this.getTimeIntervalId().equals(castOther.getTimeIntervalId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getSectionId() == null ? 0 : this.getSectionId().hashCode());
		result = 37 * result + (getGatheringDate() == null ? 0 : this.getGatheringDate().hashCode());
		result = 37 * result + (getTimeIntervalId() == null ? 0 : this.getTimeIntervalId().hashCode());
		return result;
	}

}