drop table TRF_EQPFuncIDs cascade constraints;
drop table TRF_FunctionList_t cascade constraints;
drop table TRF_OperInfoList_t cascade constraints;
drop table TRF_OperInfo_t cascade constraints;
drop table TRF_OperatorRight_t cascade constraints;
drop table TRF_OwnDeviceTypes cascade constraints;
drop table TRF_OwnRoleIDs cascade constraints;
drop table TRF_OwnStations cascade constraints;
drop table TRF_RoleFunctionList_t cascade constraints;
drop sequence S_TRF_FunctionList_t;
drop sequence S_TRF_OperInfoList_t;
drop sequence S_TRF_OperInfo_t;
drop sequence S_TRF_OperatorRight_t;
drop sequence S_TRF_RoleFunctionList_t;
create table TRF_EQPFuncIDs (TRF_RoleFunctionList_t_id number(19,0) not null, EQPFuncIDs number(19,0), index_col number(10,0) not null, primary key (TRF_RoleFunctionList_t_id, index_col));
create table TRF_FunctionList_t (RECORDID number(19,0) not null, VERSIONNUMBER number(19,0), EQPFuncID number(19,0), EQPFuncDesc varchar2(255), TRF_OperatorRight_t_id number(19,0), index_col number(10,0), nodeNo number(19,0),primary key (RECORDID));
create table TRF_OperInfoList_t (RECORDID number(19,0) not null, VERSIONNUMBER number(19,0), nodeNo number(19,0), primary key (RECORDID));
create table TRF_OperInfo_t (RECORDID number(19,0) not null, VERSIONNUMBER number(19,0), OperatorID number(19,0), OperatorName varchar2(255), OperatorPassword varchar2(255), OperatorEnableTag number(10,0), StartEnableTime timestamp, EndEnableTime timestamp, Accesslevel number(5,0), TRF_OperInfoList_t_id number(19,0), index_col number(10,0), nodeNo number(19,0), primary key (RECORDID));
create table TRF_OperatorRight_t (RECORDID number(19,0) not null, VERSIONNUMBER number(19,0), nodeNo number(19,0), primary key (RECORDID));
create table TRF_OwnDeviceTypes (TRF_OperInfo_t_id number(19,0) not null, OwnDeviceTypes number(10,0), index_col number(10,0) not null, primary key (TRF_OperInfo_t_id, index_col));
create table TRF_OwnRoleIDs (TRF_OperInfo_t_id number(19,0) not null, OwnRoleIDs number(10,0), index_col number(10,0) not null, primary key (TRF_OperInfo_t_id, index_col));
create table TRF_OwnStations (TRF_OperInfo_t_id number(19,0) not null, OwnStations number(10,0), index_col number(10,0) not null, primary key (TRF_OperInfo_t_id, index_col));
create table TRF_RoleFunctionList_t (RECORDID number(19,0) not null, VERSIONNUMBER number(19,0),  RoleID number(10,0), RoleDesc varchar2(255), TRF_OperatorRight_t_id number(19,0), index_col number(10,0), nodeNo number(19,0),primary key (RECORDID));
alter table TRF_EQPFuncIDs add constraint FK5AD7D6C79A70D715 foreign key (TRF_RoleFunctionList_t_id) references TRF_RoleFunctionList_t on delete cascade ;
alter table TRF_FunctionList_t add constraint FKD27A5EC23FBFF39F foreign key (TRF_OperatorRight_t_id) references TRF_OperatorRight_t on delete cascade;
alter table TRF_OperInfo_t add constraint FK2BF74448E5E485D5 foreign key (TRF_OperInfoList_t_id) references TRF_OperInfoList_t on delete cascade;
alter table TRF_OwnDeviceTypes add constraint FK441F2C141C503BF5 foreign key (TRF_OperInfo_t_id) references TRF_OperInfo_t on delete cascade;
alter table TRF_OwnRoleIDs add constraint FK84B46B531C503BF5 foreign key (TRF_OperInfo_t_id) references TRF_OperInfo_t on delete cascade;
alter table TRF_OwnStations add constraint FK7056930E1C503BF5 foreign key (TRF_OperInfo_t_id) references TRF_OperInfo_t on delete cascade;
alter table TRF_RoleFunctionList_t add constraint FKD8BAF1583FBFF39F foreign key (TRF_OperatorRight_t_id) references TRF_OperatorRight_t on delete cascade;
create sequence S_TRF_FunctionList_t  minvalue 1 maxvalue 999999999999999999999999999 start with 1 increment by 1 cache 20;
create sequence S_TRF_OperInfoList_t  minvalue 1 maxvalue 999999999999999999999999999 start with 1 increment by 1 cache 20;
create sequence S_TRF_OperInfo_t  minvalue 1 maxvalue 999999999999999999999999999 start with 1 increment by 1 cache 20;
create sequence S_TRF_OperatorRight_t  minvalue 1 maxvalue 999999999999999999999999999 start with 1 increment by 1 cache 20;
create sequence S_TRF_RoleFunctionList_t  minvalue 1 maxvalue 999999999999999999999999999 start with 1 increment by 1 cache 20;
comment on column TRF_FunctionList_t.EQPFuncID is ' 功能编号 ';
comment on column TRF_FunctionList_t.EQPFuncDesc is ' 功能名称';
--comment on column TRF_OperatorRight_t.RoleFunctions is ' 角色功能列表';
--comment on column TRF_OperatorRight_t.FunctionLists is ' 功能列表';
comment on column TRF_OperInfo_t.OperatorID is ' 用户编号 ';
comment on column TRF_OperInfo_t.OperatorName is '用户名称';
comment on column TRF_OperInfo_t.OperatorPassword is ' 用户密码 ';
comment on column TRF_OperInfo_t.OperatorEnableTag is ' 启用标志位 0不启用，1启用 ';
comment on column TRF_OperInfo_t.StartEnableTime is ' 启用时间 ';
comment on column TRF_OperInfo_t.EndEnableTime is ' 截至时间 ';
comment on column TRF_OperInfo_t.Accesslevel is ' 用户权限等级 ';
--comment on column TRF_OperInfo_t.OwnRoleIDs is ' 配置角色列表 ';
--comment on column TRF_OperInfo_t.OwnStations is ' 配置车站列表 ';
--comment on column TRF_OperInfo_t.OwnDeviceTypes is ' 配置终端设备类型列表 ';
--comment on column TRF_OperInfoList_t.OperInfoList is ' 操作员基本信息列表 ';
comment on column TRF_RoleFunctionList_t.RoleID is ' 角色编号 ';
comment on column TRF_RoleFunctionList_t.RoleDesc is ' 角色描述 ';
--comment on column TRF_RoleFunctionList_t.EQPFuncIDs is ' 角色功能列表 ';
