package com.insigma.afc.monitor.model.entity;

import javax.persistence.*;
import java.util.Date;

/**
 * TmoSectionOdFlowStats generated by MyEclipse Persistence Tools
 */
@Entity
@Table(name = "TMO_SECTION_OD_FLOW_STATS")
@IdClass(TmoSectionOdFlowStatsId.class)
public class TmoSectionOdFlowStats implements java.io.Serializable {

	private static final long serialVersionUID = 1994886518071062439L;

	@Id
	@Column(name = "SECTION_ID", length = 19, nullable = false)
	private Long sectionId;

	@Id
	@Temporal(TemporalType.DATE)
	@Column(name = "GATHERING_DATE", length = 11, nullable = false)
	private Date gatheringDate;

	@Id
	@Column(name = "TIME_INTERVAL_ID", length = 11, nullable = false)
	private Long timeIntervalId;

	@Column(name = "UP_COUNT", length = 20)
	private Long upCount;

	@Column(name = "DOWN_COUNT", length = 20)
	private Long downCount;

	@Column(name = "TOTAL_COUNT", length = 20)
	private Long totalCount;

	public Long getSectionId() {
		return sectionId;
	}

	public void setSectionId(Long sectionId) {
		this.sectionId = sectionId;
	}

	public Date getGatheringDate() {
		return gatheringDate;
	}

	public void setGatheringDate(Date gatheringDate) {
		this.gatheringDate = gatheringDate;
	}

	public Long getTimeIntervalId() {
		return timeIntervalId;
	}

	public void setTimeIntervalId(Long timeIntervalId) {
		this.timeIntervalId = timeIntervalId;
	}

	public Long getUpCount() {
		return this.upCount;
	}

	public void setUpCount(Long upCount) {
		this.upCount = upCount;
	}

	public Long getDownCount() {
		return this.downCount;
	}

	public void setDownCount(Long downCount) {
		this.downCount = downCount;
	}

	public Long getTotalCount() {
		return this.totalCount;
	}

	public void setTotalCount(Long totalCount) {
		this.totalCount = totalCount;
	}

}
